// Code generated by go-swagger; DO NOT EDIT.

package b_a_cnet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetBACnetServerReader is a Reader for the GetBACnetServer structure.
type GetBACnetServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBACnetServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBACnetServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/bacnet/server] GetBACnetServer", response, response.Code())
	}
}

// NewGetBACnetServerOK creates a GetBACnetServerOK with default headers values
func NewGetBACnetServerOK() *GetBACnetServerOK {
	return &GetBACnetServerOK{}
}

/*
GetBACnetServerOK describes a response with status code 200, with default header values.

GetBACnetServerOK get b a cnet server o k
*/
type GetBACnetServerOK struct {
	Payload *models.APIGetBACnetServerResponse
}

// IsSuccess returns true when this get b a cnet server o k response has a 2xx status code
func (o *GetBACnetServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get b a cnet server o k response has a 3xx status code
func (o *GetBACnetServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get b a cnet server o k response has a 4xx status code
func (o *GetBACnetServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get b a cnet server o k response has a 5xx status code
func (o *GetBACnetServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get b a cnet server o k response a status code equal to that given
func (o *GetBACnetServerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get b a cnet server o k response
func (o *GetBACnetServerOK) Code() int {
	return 200
}

func (o *GetBACnetServerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/bacnet/server][%d] getBACnetServerOK %s", 200, payload)
}

func (o *GetBACnetServerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/bacnet/server][%d] getBACnetServerOK %s", 200, payload)
}

func (o *GetBACnetServerOK) GetPayload() *models.APIGetBACnetServerResponse {
	return o.Payload
}

func (o *GetBACnetServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetBACnetServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
