// Code generated by go-swagger; DO NOT EDIT.

package b_a_cnet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIBacnetDeleteDeveuiReader is a Reader for the PostAPIBacnetDeleteDeveui structure.
type PostAPIBacnetDeleteDeveuiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIBacnetDeleteDeveuiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIBacnetDeleteDeveuiOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/bacnet/delete/deveui] post_api_bacnet_delete_deveui", response, response.Code())
	}
}

// NewPostAPIBacnetDeleteDeveuiOK creates a PostAPIBacnetDeleteDeveuiOK with default headers values
func NewPostAPIBacnetDeleteDeveuiOK() *PostAPIBacnetDeleteDeveuiOK {
	return &PostAPIBacnetDeleteDeveuiOK{}
}

/*
PostAPIBacnetDeleteDeveuiOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIBacnetDeleteDeveuiOK struct {
	Payload *models.APIDeleteBACnetObjectsByDevEUIResponse
}

// IsSuccess returns true when this post Api bacnet delete deveui o k response has a 2xx status code
func (o *PostAPIBacnetDeleteDeveuiOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api bacnet delete deveui o k response has a 3xx status code
func (o *PostAPIBacnetDeleteDeveuiOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api bacnet delete deveui o k response has a 4xx status code
func (o *PostAPIBacnetDeleteDeveuiOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api bacnet delete deveui o k response has a 5xx status code
func (o *PostAPIBacnetDeleteDeveuiOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api bacnet delete deveui o k response a status code equal to that given
func (o *PostAPIBacnetDeleteDeveuiOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api bacnet delete deveui o k response
func (o *PostAPIBacnetDeleteDeveuiOK) Code() int {
	return 200
}

func (o *PostAPIBacnetDeleteDeveuiOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/bacnet/delete/deveui][%d] postApiBacnetDeleteDeveuiOK %s", 200, payload)
}

func (o *PostAPIBacnetDeleteDeveuiOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/bacnet/delete/deveui][%d] postApiBacnetDeleteDeveuiOK %s", 200, payload)
}

func (o *PostAPIBacnetDeleteDeveuiOK) GetPayload() *models.APIDeleteBACnetObjectsByDevEUIResponse {
	return o.Payload
}

func (o *PostAPIBacnetDeleteDeveuiOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIDeleteBACnetObjectsByDevEUIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
