// Code generated by go-swagger; DO NOT EDIT.

package b_a_cnet_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PutAPIBacnetServerReader is a Reader for the PutAPIBacnetServer structure.
type PutAPIBacnetServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIBacnetServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIBacnetServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/bacnet/server] put_api_bacnet_server", response, response.Code())
	}
}

// NewPutAPIBacnetServerOK creates a PutAPIBacnetServerOK with default headers values
func NewPutAPIBacnetServerOK() *PutAPIBacnetServerOK {
	return &PutAPIBacnetServerOK{}
}

/*
PutAPIBacnetServerOK describes a response with status code 200, with default header values.

(empty)
*/
type PutAPIBacnetServerOK struct {
	Payload *models.APIUpdateBACnetServerResponse
}

// IsSuccess returns true when this put Api bacnet server o k response has a 2xx status code
func (o *PutAPIBacnetServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api bacnet server o k response has a 3xx status code
func (o *PutAPIBacnetServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api bacnet server o k response has a 4xx status code
func (o *PutAPIBacnetServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api bacnet server o k response has a 5xx status code
func (o *PutAPIBacnetServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api bacnet server o k response a status code equal to that given
func (o *PutAPIBacnetServerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api bacnet server o k response
func (o *PutAPIBacnetServerOK) Code() int {
	return 200
}

func (o *PutAPIBacnetServerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/bacnet/server][%d] putApiBacnetServerOK %s", 200, payload)
}

func (o *PutAPIBacnetServerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/bacnet/server][%d] putApiBacnetServerOK %s", 200, payload)
}

func (o *PutAPIBacnetServerOK) GetPayload() *models.APIUpdateBACnetServerResponse {
	return o.Payload
}

func (o *PutAPIBacnetServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUpdateBACnetServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
