// Code generated by go-swagger; DO NOT EDIT.

package network_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPINetworkServersByIDReader is a Reader for the GetAPINetworkServersByID structure.
type GetAPINetworkServersByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPINetworkServersByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPINetworkServersByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/network-servers/{id}] get_api_network-servers_by_id", response, response.Code())
	}
}

// NewGetAPINetworkServersByIDOK creates a GetAPINetworkServersByIDOK with default headers values
func NewGetAPINetworkServersByIDOK() *GetAPINetworkServersByIDOK {
	return &GetAPINetworkServersByIDOK{}
}

/*
GetAPINetworkServersByIDOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPINetworkServersByIDOK struct {
	Payload *models.APIGetNetworkServerResponse
}

// IsSuccess returns true when this get Api network servers by Id o k response has a 2xx status code
func (o *GetAPINetworkServersByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api network servers by Id o k response has a 3xx status code
func (o *GetAPINetworkServersByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api network servers by Id o k response has a 4xx status code
func (o *GetAPINetworkServersByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api network servers by Id o k response has a 5xx status code
func (o *GetAPINetworkServersByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api network servers by Id o k response a status code equal to that given
func (o *GetAPINetworkServersByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api network servers by Id o k response
func (o *GetAPINetworkServersByIDOK) Code() int {
	return 200
}

func (o *GetAPINetworkServersByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/network-servers/{id}][%d] getApiNetworkServersByIdOK %s", 200, payload)
}

func (o *GetAPINetworkServersByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/network-servers/{id}][%d] getApiNetworkServersByIdOK %s", 200, payload)
}

func (o *GetAPINetworkServersByIDOK) GetPayload() *models.APIGetNetworkServerResponse {
	return o.Payload
}

func (o *GetAPINetworkServersByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetNetworkServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
