// Code generated by go-swagger; DO NOT EDIT.

package network_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPINetworkServersReader is a Reader for the GetAPINetworkServers structure.
type GetAPINetworkServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPINetworkServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPINetworkServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/network-servers] get_api_network-servers", response, response.Code())
	}
}

// NewGetAPINetworkServersOK creates a GetAPINetworkServersOK with default headers values
func NewGetAPINetworkServersOK() *GetAPINetworkServersOK {
	return &GetAPINetworkServersOK{}
}

/*
GetAPINetworkServersOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPINetworkServersOK struct {
	Payload *models.APIListNetworkServerResponse
}

// IsSuccess returns true when this get Api network servers o k response has a 2xx status code
func (o *GetAPINetworkServersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api network servers o k response has a 3xx status code
func (o *GetAPINetworkServersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api network servers o k response has a 4xx status code
func (o *GetAPINetworkServersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api network servers o k response has a 5xx status code
func (o *GetAPINetworkServersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api network servers o k response a status code equal to that given
func (o *GetAPINetworkServersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api network servers o k response
func (o *GetAPINetworkServersOK) Code() int {
	return 200
}

func (o *GetAPINetworkServersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/network-servers][%d] getApiNetworkServersOK %s", 200, payload)
}

func (o *GetAPINetworkServersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/network-servers][%d] getApiNetworkServersOK %s", 200, payload)
}

func (o *GetAPINetworkServersOK) GetPayload() *models.APIListNetworkServerResponse {
	return o.Payload
}

func (o *GetAPINetworkServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIListNetworkServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
