// Code generated by go-swagger; DO NOT EDIT.

package network_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new network server API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new network server API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new network server API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for network server API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPINetworkServersByID(params *DeleteAPINetworkServersByIDParams, opts ...ClientOption) (*DeleteAPINetworkServersByIDOK, error)

	GetAPINetworkServerSettings(params *GetAPINetworkServerSettingsParams, opts ...ClientOption) (*GetAPINetworkServerSettingsOK, error)

	GetAPINetworkServers(params *GetAPINetworkServersParams, opts ...ClientOption) (*GetAPINetworkServersOK, error)

	GetAPINetworkServersByID(params *GetAPINetworkServersByIDParams, opts ...ClientOption) (*GetAPINetworkServersByIDOK, error)

	PostAPINetworkServerSettings(params *PostAPINetworkServerSettingsParams, opts ...ClientOption) (*PostAPINetworkServerSettingsOK, error)

	PostAPINetworkServers(params *PostAPINetworkServersParams, opts ...ClientOption) (*PostAPINetworkServersOK, error)

	PutAPINetworkServersByID(params *PutAPINetworkServersByIDParams, opts ...ClientOption) (*PutAPINetworkServersByIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPINetworkServersByID deletes deletes the network server matching the given id
*/
func (a *Client) DeleteAPINetworkServersByID(params *DeleteAPINetworkServersByIDParams, opts ...ClientOption) (*DeleteAPINetworkServersByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAPINetworkServersByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete_api_network-servers_by_id",
		Method:             "DELETE",
		PathPattern:        "/api/network-servers/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteAPINetworkServersByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteAPINetworkServersByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete_api_network-servers_by_id: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPINetworkServerSettings gets general network servers general general
*/
func (a *Client) GetAPINetworkServerSettings(params *GetAPINetworkServerSettingsParams, opts ...ClientOption) (*GetAPINetworkServerSettingsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPINetworkServerSettingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_network-server_settings",
		Method:             "GET",
		PathPattern:        "/api/network-server/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPINetworkServerSettingsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPINetworkServerSettingsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_network-server_settings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPINetworkServers lists lists the available network servers
*/
func (a *Client) GetAPINetworkServers(params *GetAPINetworkServersParams, opts ...ClientOption) (*GetAPINetworkServersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPINetworkServersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_network-servers",
		Method:             "GET",
		PathPattern:        "/api/network-servers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPINetworkServersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPINetworkServersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_network-servers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPINetworkServersByID gets returns the network server matching the given id
*/
func (a *Client) GetAPINetworkServersByID(params *GetAPINetworkServersByIDParams, opts ...ClientOption) (*GetAPINetworkServersByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPINetworkServersByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_network-servers_by_id",
		Method:             "GET",
		PathPattern:        "/api/network-servers/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPINetworkServersByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPINetworkServersByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_network-servers_by_id: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPINetworkServerSettings post api network server settings API
*/
func (a *Client) PostAPINetworkServerSettings(params *PostAPINetworkServerSettingsParams, opts ...ClientOption) (*PostAPINetworkServerSettingsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAPINetworkServerSettingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "post_api_network-server_settings",
		Method:             "POST",
		PathPattern:        "/api/network-server/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostAPINetworkServerSettingsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAPINetworkServerSettingsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post_api_network-server_settings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPINetworkServers creates creates the given network server
*/
func (a *Client) PostAPINetworkServers(params *PostAPINetworkServersParams, opts ...ClientOption) (*PostAPINetworkServersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAPINetworkServersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "post_api_network-servers",
		Method:             "POST",
		PathPattern:        "/api/network-servers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostAPINetworkServersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAPINetworkServersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post_api_network-servers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPINetworkServersByID updates updates the given network server
*/
func (a *Client) PutAPINetworkServersByID(params *PutAPINetworkServersByIDParams, opts ...ClientOption) (*PutAPINetworkServersByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPINetworkServersByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "put_api_network-servers_by_id",
		Method:             "PUT",
		PathPattern:        "/api/network-servers/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutAPINetworkServersByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutAPINetworkServersByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for put_api_network-servers_by_id: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
