// Code generated by go-swagger; DO NOT EDIT.

package network_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPINetworkServersIDParams creates a new PutAPINetworkServersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPINetworkServersIDParams() *PutAPINetworkServersIDParams {
	return &PutAPINetworkServersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPINetworkServersIDParamsWithTimeout creates a new PutAPINetworkServersIDParams object
// with the ability to set a timeout on a request.
func NewPutAPINetworkServersIDParamsWithTimeout(timeout time.Duration) *PutAPINetworkServersIDParams {
	return &PutAPINetworkServersIDParams{
		timeout: timeout,
	}
}

// NewPutAPINetworkServersIDParamsWithContext creates a new PutAPINetworkServersIDParams object
// with the ability to set a context for a request.
func NewPutAPINetworkServersIDParamsWithContext(ctx context.Context) *PutAPINetworkServersIDParams {
	return &PutAPINetworkServersIDParams{
		Context: ctx,
	}
}

// NewPutAPINetworkServersIDParamsWithHTTPClient creates a new PutAPINetworkServersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPINetworkServersIDParamsWithHTTPClient(client *http.Client) *PutAPINetworkServersIDParams {
	return &PutAPINetworkServersIDParams{
		HTTPClient: client,
	}
}

/*
PutAPINetworkServersIDParams contains all the parameters to send to the API endpoint

	for the put API network servers ID operation.

	Typically these are written to a http.Request.
*/
type PutAPINetworkServersIDParams struct {

	// Body.
	Body *models.APIUpdateNetworkServerRequest

	/* ID.

	   ID of the network-server.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API network servers ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPINetworkServersIDParams) WithDefaults() *PutAPINetworkServersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API network servers ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPINetworkServersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) WithTimeout(timeout time.Duration) *PutAPINetworkServersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) WithContext(ctx context.Context) *PutAPINetworkServersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) WithHTTPClient(client *http.Client) *PutAPINetworkServersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) WithBody(body *models.APIUpdateNetworkServerRequest) *PutAPINetworkServersIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) SetBody(body *models.APIUpdateNetworkServerRequest) {
	o.Body = body
}

// WithID adds the id to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) WithID(id string) *PutAPINetworkServersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API network servers ID params
func (o *PutAPINetworkServersIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPINetworkServersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
