// Code generated by go-swagger; DO NOT EDIT.

package ursalink_device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// DeleteAPIUrdevicesallReader is a Reader for the DeleteAPIUrdevicesall structure.
type DeleteAPIUrdevicesallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIUrdevicesallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIUrdevicesallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/urdevicesall] delete_api_urdevicesall", response, response.Code())
	}
}

// NewDeleteAPIUrdevicesallOK creates a DeleteAPIUrdevicesallOK with default headers values
func NewDeleteAPIUrdevicesallOK() *DeleteAPIUrdevicesallOK {
	return &DeleteAPIUrdevicesallOK{}
}

/*
DeleteAPIUrdevicesallOK describes a response with status code 200, with default header values.

(empty)
*/
type DeleteAPIUrdevicesallOK struct {
	Payload models.APIUrDeleteAllDeviceResponse
}

// IsSuccess returns true when this delete Api urdevicesall o k response has a 2xx status code
func (o *DeleteAPIUrdevicesallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api urdevicesall o k response has a 3xx status code
func (o *DeleteAPIUrdevicesallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api urdevicesall o k response has a 4xx status code
func (o *DeleteAPIUrdevicesallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api urdevicesall o k response has a 5xx status code
func (o *DeleteAPIUrdevicesallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api urdevicesall o k response a status code equal to that given
func (o *DeleteAPIUrdevicesallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api urdevicesall o k response
func (o *DeleteAPIUrdevicesallOK) Code() int {
	return 200
}

func (o *DeleteAPIUrdevicesallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/urdevicesall][%d] deleteApiUrdevicesallOK %s", 200, payload)
}

func (o *DeleteAPIUrdevicesallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/urdevicesall][%d] deleteApiUrdevicesallOK %s", 200, payload)
}

func (o *DeleteAPIUrdevicesallOK) GetPayload() models.APIUrDeleteAllDeviceResponse {
	return o.Payload
}

func (o *DeleteAPIUrdevicesallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
