// Code generated by go-swagger; DO NOT EDIT.

package ursalink_device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIUrdevicesReader is a Reader for the GetAPIUrdevices structure.
type GetAPIUrdevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIUrdevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIUrdevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/urdevices] get_api_urdevices", response, response.Code())
	}
}

// NewGetAPIUrdevicesOK creates a GetAPIUrdevicesOK with default headers values
func NewGetAPIUrdevicesOK() *GetAPIUrdevicesOK {
	return &GetAPIUrdevicesOK{}
}

/*
GetAPIUrdevicesOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIUrdevicesOK struct {
	Payload *models.APIUrListDeviceResponse
}

// IsSuccess returns true when this get Api urdevices o k response has a 2xx status code
func (o *GetAPIUrdevicesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api urdevices o k response has a 3xx status code
func (o *GetAPIUrdevicesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api urdevices o k response has a 4xx status code
func (o *GetAPIUrdevicesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api urdevices o k response has a 5xx status code
func (o *GetAPIUrdevicesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api urdevices o k response a status code equal to that given
func (o *GetAPIUrdevicesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api urdevices o k response
func (o *GetAPIUrdevicesOK) Code() int {
	return 200
}

func (o *GetAPIUrdevicesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/urdevices][%d] getApiUrdevicesOK %s", 200, payload)
}

func (o *GetAPIUrdevicesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/urdevices][%d] getApiUrdevicesOK %s", 200, payload)
}

func (o *GetAPIUrdevicesOK) GetPayload() *models.APIUrListDeviceResponse {
	return o.Payload
}

func (o *GetAPIUrdevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUrListDeviceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
