// Code generated by go-swagger; DO NOT EDIT.

package ursalink_device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// ListSimpleReader is a Reader for the ListSimple structure.
type ListSimpleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSimpleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSimpleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/urdevices/simple] ListSimple", response, response.Code())
	}
}

// NewListSimpleOK creates a ListSimpleOK with default headers values
func NewListSimpleOK() *ListSimpleOK {
	return &ListSimpleOK{}
}

/*
ListSimpleOK describes a response with status code 200, with default header values.

ListSimpleOK list simple o k
*/
type ListSimpleOK struct {
	Payload *models.APIUrListSimpleDeviceResponse
}

// IsSuccess returns true when this list simple o k response has a 2xx status code
func (o *ListSimpleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list simple o k response has a 3xx status code
func (o *ListSimpleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list simple o k response has a 4xx status code
func (o *ListSimpleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list simple o k response has a 5xx status code
func (o *ListSimpleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list simple o k response a status code equal to that given
func (o *ListSimpleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list simple o k response
func (o *ListSimpleOK) Code() int {
	return 200
}

func (o *ListSimpleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/urdevices/simple][%d] listSimpleOK %s", 200, payload)
}

func (o *ListSimpleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/urdevices/simple][%d] listSimpleOK %s", 200, payload)
}

func (o *ListSimpleOK) GetPayload() *models.APIUrListSimpleDeviceResponse {
	return o.Payload
}

func (o *ListSimpleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUrListSimpleDeviceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
