// Code generated by go-swagger; DO NOT EDIT.

package ursalink_device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIUrdevicesDevEUIParams creates a new PutAPIUrdevicesDevEUIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIUrdevicesDevEUIParams() *PutAPIUrdevicesDevEUIParams {
	return &PutAPIUrdevicesDevEUIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIUrdevicesDevEUIParamsWithTimeout creates a new PutAPIUrdevicesDevEUIParams object
// with the ability to set a timeout on a request.
func NewPutAPIUrdevicesDevEUIParamsWithTimeout(timeout time.Duration) *PutAPIUrdevicesDevEUIParams {
	return &PutAPIUrdevicesDevEUIParams{
		timeout: timeout,
	}
}

// NewPutAPIUrdevicesDevEUIParamsWithContext creates a new PutAPIUrdevicesDevEUIParams object
// with the ability to set a context for a request.
func NewPutAPIUrdevicesDevEUIParamsWithContext(ctx context.Context) *PutAPIUrdevicesDevEUIParams {
	return &PutAPIUrdevicesDevEUIParams{
		Context: ctx,
	}
}

// NewPutAPIUrdevicesDevEUIParamsWithHTTPClient creates a new PutAPIUrdevicesDevEUIParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIUrdevicesDevEUIParamsWithHTTPClient(client *http.Client) *PutAPIUrdevicesDevEUIParams {
	return &PutAPIUrdevicesDevEUIParams{
		HTTPClient: client,
	}
}

/*
PutAPIUrdevicesDevEUIParams contains all the parameters to send to the API endpoint

	for the put API urdevices dev e UI operation.

	Typically these are written to a http.Request.
*/
type PutAPIUrdevicesDevEUIParams struct {

	// Body.
	Body *models.APIUrUpdateDeviceRequest

	/* DevEUI.

	   Hex encoded DevEUI.
	*/
	DevEUI string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API urdevices dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUrdevicesDevEUIParams) WithDefaults() *PutAPIUrdevicesDevEUIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API urdevices dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUrdevicesDevEUIParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) WithTimeout(timeout time.Duration) *PutAPIUrdevicesDevEUIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) WithContext(ctx context.Context) *PutAPIUrdevicesDevEUIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) WithHTTPClient(client *http.Client) *PutAPIUrdevicesDevEUIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) WithBody(body *models.APIUrUpdateDeviceRequest) *PutAPIUrdevicesDevEUIParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) SetBody(body *models.APIUrUpdateDeviceRequest) {
	o.Body = body
}

// WithDevEUI adds the devEUI to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) WithDevEUI(devEUI string) *PutAPIUrdevicesDevEUIParams {
	o.SetDevEUI(devEUI)
	return o
}

// SetDevEUI adds the devEUi to the put API urdevices dev e UI params
func (o *PutAPIUrdevicesDevEUIParams) SetDevEUI(devEUI string) {
	o.DevEUI = devEUI
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIUrdevicesDevEUIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param devEUI
	if err := r.SetPathParam("devEUI", o.DevEUI); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
