// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIOrganizationsReader is a Reader for the PostAPIOrganizations structure.
type PostAPIOrganizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIOrganizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIOrganizationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/organizations] post_api_organizations", response, response.Code())
	}
}

// NewPostAPIOrganizationsOK creates a PostAPIOrganizationsOK with default headers values
func NewPostAPIOrganizationsOK() *PostAPIOrganizationsOK {
	return &PostAPIOrganizationsOK{}
}

/*
PostAPIOrganizationsOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIOrganizationsOK struct {
	Payload *models.APICreateOrganizationResponse
}

// IsSuccess returns true when this post Api organizations o k response has a 2xx status code
func (o *PostAPIOrganizationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api organizations o k response has a 3xx status code
func (o *PostAPIOrganizationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api organizations o k response has a 4xx status code
func (o *PostAPIOrganizationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api organizations o k response has a 5xx status code
func (o *PostAPIOrganizationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api organizations o k response a status code equal to that given
func (o *PostAPIOrganizationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api organizations o k response
func (o *PostAPIOrganizationsOK) Code() int {
	return 200
}

func (o *PostAPIOrganizationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/organizations][%d] postApiOrganizationsOK %s", 200, payload)
}

func (o *PostAPIOrganizationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/organizations][%d] postApiOrganizationsOK %s", 200, payload)
}

func (o *PostAPIOrganizationsOK) GetPayload() *models.APICreateOrganizationResponse {
	return o.Payload
}

func (o *PostAPIOrganizationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICreateOrganizationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
