// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIOrganizationsParams creates a new PostAPIOrganizationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIOrganizationsParams() *PostAPIOrganizationsParams {
	return &PostAPIOrganizationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIOrganizationsParamsWithTimeout creates a new PostAPIOrganizationsParams object
// with the ability to set a timeout on a request.
func NewPostAPIOrganizationsParamsWithTimeout(timeout time.Duration) *PostAPIOrganizationsParams {
	return &PostAPIOrganizationsParams{
		timeout: timeout,
	}
}

// NewPostAPIOrganizationsParamsWithContext creates a new PostAPIOrganizationsParams object
// with the ability to set a context for a request.
func NewPostAPIOrganizationsParamsWithContext(ctx context.Context) *PostAPIOrganizationsParams {
	return &PostAPIOrganizationsParams{
		Context: ctx,
	}
}

// NewPostAPIOrganizationsParamsWithHTTPClient creates a new PostAPIOrganizationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIOrganizationsParamsWithHTTPClient(client *http.Client) *PostAPIOrganizationsParams {
	return &PostAPIOrganizationsParams{
		HTTPClient: client,
	}
}

/*
PostAPIOrganizationsParams contains all the parameters to send to the API endpoint

	for the post api organizations operation.

	Typically these are written to a http.Request.
*/
type PostAPIOrganizationsParams struct {

	// Body.
	Body *models.APICreateOrganizationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api organizations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOrganizationsParams) WithDefaults() *PostAPIOrganizationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api organizations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOrganizationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api organizations params
func (o *PostAPIOrganizationsParams) WithTimeout(timeout time.Duration) *PostAPIOrganizationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api organizations params
func (o *PostAPIOrganizationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api organizations params
func (o *PostAPIOrganizationsParams) WithContext(ctx context.Context) *PostAPIOrganizationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api organizations params
func (o *PostAPIOrganizationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api organizations params
func (o *PostAPIOrganizationsParams) WithHTTPClient(client *http.Client) *PostAPIOrganizationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api organizations params
func (o *PostAPIOrganizationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api organizations params
func (o *PostAPIOrganizationsParams) WithBody(body *models.APICreateOrganizationRequest) *PostAPIOrganizationsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api organizations params
func (o *PostAPIOrganizationsParams) SetBody(body *models.APICreateOrganizationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIOrganizationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
