// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIOrganizationsUsersByIDParams creates a new PostAPIOrganizationsUsersByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIOrganizationsUsersByIDParams() *PostAPIOrganizationsUsersByIDParams {
	return &PostAPIOrganizationsUsersByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIOrganizationsUsersByIDParamsWithTimeout creates a new PostAPIOrganizationsUsersByIDParams object
// with the ability to set a timeout on a request.
func NewPostAPIOrganizationsUsersByIDParamsWithTimeout(timeout time.Duration) *PostAPIOrganizationsUsersByIDParams {
	return &PostAPIOrganizationsUsersByIDParams{
		timeout: timeout,
	}
}

// NewPostAPIOrganizationsUsersByIDParamsWithContext creates a new PostAPIOrganizationsUsersByIDParams object
// with the ability to set a context for a request.
func NewPostAPIOrganizationsUsersByIDParamsWithContext(ctx context.Context) *PostAPIOrganizationsUsersByIDParams {
	return &PostAPIOrganizationsUsersByIDParams{
		Context: ctx,
	}
}

// NewPostAPIOrganizationsUsersByIDParamsWithHTTPClient creates a new PostAPIOrganizationsUsersByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIOrganizationsUsersByIDParamsWithHTTPClient(client *http.Client) *PostAPIOrganizationsUsersByIDParams {
	return &PostAPIOrganizationsUsersByIDParams{
		HTTPClient: client,
	}
}

/*
PostAPIOrganizationsUsersByIDParams contains all the parameters to send to the API endpoint

	for the post api organizations users by id operation.

	Typically these are written to a http.Request.
*/
type PostAPIOrganizationsUsersByIDParams struct {

	// Body.
	Body *models.APIOrganizationUserRequest

	/* ID.

	   The organization id.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api organizations users by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOrganizationsUsersByIDParams) WithDefaults() *PostAPIOrganizationsUsersByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api organizations users by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIOrganizationsUsersByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) WithTimeout(timeout time.Duration) *PostAPIOrganizationsUsersByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) WithContext(ctx context.Context) *PostAPIOrganizationsUsersByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) WithHTTPClient(client *http.Client) *PostAPIOrganizationsUsersByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) WithBody(body *models.APIOrganizationUserRequest) *PostAPIOrganizationsUsersByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) SetBody(body *models.APIOrganizationUserRequest) {
	o.Body = body
}

// WithID adds the id to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) WithID(id string) *PostAPIOrganizationsUsersByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post api organizations users by id params
func (o *PostAPIOrganizationsUsersByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIOrganizationsUsersByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
