// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteURHTTPIntegrationParams creates a new DeleteURHTTPIntegrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteURHTTPIntegrationParams() *DeleteURHTTPIntegrationParams {
	return &DeleteURHTTPIntegrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteURHTTPIntegrationParamsWithTimeout creates a new DeleteURHTTPIntegrationParams object
// with the ability to set a timeout on a request.
func NewDeleteURHTTPIntegrationParamsWithTimeout(timeout time.Duration) *DeleteURHTTPIntegrationParams {
	return &DeleteURHTTPIntegrationParams{
		timeout: timeout,
	}
}

// NewDeleteURHTTPIntegrationParamsWithContext creates a new DeleteURHTTPIntegrationParams object
// with the ability to set a context for a request.
func NewDeleteURHTTPIntegrationParamsWithContext(ctx context.Context) *DeleteURHTTPIntegrationParams {
	return &DeleteURHTTPIntegrationParams{
		Context: ctx,
	}
}

// NewDeleteURHTTPIntegrationParamsWithHTTPClient creates a new DeleteURHTTPIntegrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteURHTTPIntegrationParamsWithHTTPClient(client *http.Client) *DeleteURHTTPIntegrationParams {
	return &DeleteURHTTPIntegrationParams{
		HTTPClient: client,
	}
}

/*
DeleteURHTTPIntegrationParams contains all the parameters to send to the API endpoint

	for the delete u r HTTP integration operation.

	Typically these are written to a http.Request.
*/
type DeleteURHTTPIntegrationParams struct {

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete u r HTTP integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteURHTTPIntegrationParams) WithDefaults() *DeleteURHTTPIntegrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete u r HTTP integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteURHTTPIntegrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) WithTimeout(timeout time.Duration) *DeleteURHTTPIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) WithContext(ctx context.Context) *DeleteURHTTPIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) WithHTTPClient(client *http.Client) *DeleteURHTTPIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) WithID(id string) *DeleteURHTTPIntegrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete u r HTTP integration params
func (o *DeleteURHTTPIntegrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteURHTTPIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
