// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIUrapplicationsParams creates a new GetAPIUrapplicationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIUrapplicationsParams() *GetAPIUrapplicationsParams {
	return &GetAPIUrapplicationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIUrapplicationsParamsWithTimeout creates a new GetAPIUrapplicationsParams object
// with the ability to set a timeout on a request.
func NewGetAPIUrapplicationsParamsWithTimeout(timeout time.Duration) *GetAPIUrapplicationsParams {
	return &GetAPIUrapplicationsParams{
		timeout: timeout,
	}
}

// NewGetAPIUrapplicationsParamsWithContext creates a new GetAPIUrapplicationsParams object
// with the ability to set a context for a request.
func NewGetAPIUrapplicationsParamsWithContext(ctx context.Context) *GetAPIUrapplicationsParams {
	return &GetAPIUrapplicationsParams{
		Context: ctx,
	}
}

// NewGetAPIUrapplicationsParamsWithHTTPClient creates a new GetAPIUrapplicationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIUrapplicationsParamsWithHTTPClient(client *http.Client) *GetAPIUrapplicationsParams {
	return &GetAPIUrapplicationsParams{
		HTTPClient: client,
	}
}

/*
GetAPIUrapplicationsParams contains all the parameters to send to the API endpoint

	for the get api urapplications operation.

	Typically these are written to a http.Request.
*/
type GetAPIUrapplicationsParams struct {

	/* Limit.

	   Max number of applications to return in the result-test.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset in the result-set (for pagination).

	   Format: int64
	*/
	Offset *string

	/* OrganizationID.

	   ID of the organization to filter on.

	   Format: int64
	*/
	OrganizationID *string

	/* Search.

	   Search on name (optional).
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get api urapplications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUrapplicationsParams) WithDefaults() *GetAPIUrapplicationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get api urapplications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIUrapplicationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithTimeout(timeout time.Duration) *GetAPIUrapplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithContext(ctx context.Context) *GetAPIUrapplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithHTTPClient(client *http.Client) *GetAPIUrapplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithLimit(limit *string) *GetAPIUrapplicationsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithOffset(offset *string) *GetAPIUrapplicationsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithOrganizationID(organizationID *string) *GetAPIUrapplicationsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WithSearch adds the search to the get api urapplications params
func (o *GetAPIUrapplicationsParams) WithSearch(search *string) *GetAPIUrapplicationsParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get api urapplications params
func (o *GetAPIUrapplicationsParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIUrapplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationID
		var qrOrganizationID string

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationID", qOrganizationID); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
