// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetURMQTTIntergrationParams creates a new GetURMQTTIntergrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetURMQTTIntergrationParams() *GetURMQTTIntergrationParams {
	return &GetURMQTTIntergrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetURMQTTIntergrationParamsWithTimeout creates a new GetURMQTTIntergrationParams object
// with the ability to set a timeout on a request.
func NewGetURMQTTIntergrationParamsWithTimeout(timeout time.Duration) *GetURMQTTIntergrationParams {
	return &GetURMQTTIntergrationParams{
		timeout: timeout,
	}
}

// NewGetURMQTTIntergrationParamsWithContext creates a new GetURMQTTIntergrationParams object
// with the ability to set a context for a request.
func NewGetURMQTTIntergrationParamsWithContext(ctx context.Context) *GetURMQTTIntergrationParams {
	return &GetURMQTTIntergrationParams{
		Context: ctx,
	}
}

// NewGetURMQTTIntergrationParamsWithHTTPClient creates a new GetURMQTTIntergrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetURMQTTIntergrationParamsWithHTTPClient(client *http.Client) *GetURMQTTIntergrationParams {
	return &GetURMQTTIntergrationParams{
		HTTPClient: client,
	}
}

/*
GetURMQTTIntergrationParams contains all the parameters to send to the API endpoint

	for the get u r m q t t intergration operation.

	Typically these are written to a http.Request.
*/
type GetURMQTTIntergrationParams struct {

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get u r m q t t intergration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetURMQTTIntergrationParams) WithDefaults() *GetURMQTTIntergrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get u r m q t t intergration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetURMQTTIntergrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) WithTimeout(timeout time.Duration) *GetURMQTTIntergrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) WithContext(ctx context.Context) *GetURMQTTIntergrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) WithHTTPClient(client *http.Client) *GetURMQTTIntergrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) WithID(id string) *GetURMQTTIntergrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get u r m q t t intergration params
func (o *GetURMQTTIntergrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetURMQTTIntergrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
