// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIUrapplicationsReader is a Reader for the PostAPIUrapplications structure.
type PostAPIUrapplicationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIUrapplicationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIUrapplicationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/urapplications] post_api_urapplications", response, response.Code())
	}
}

// NewPostAPIUrapplicationsOK creates a PostAPIUrapplicationsOK with default headers values
func NewPostAPIUrapplicationsOK() *PostAPIUrapplicationsOK {
	return &PostAPIUrapplicationsOK{}
}

/*
PostAPIUrapplicationsOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIUrapplicationsOK struct {
	Payload *models.APIURCreateApplicationResponse
}

// IsSuccess returns true when this post Api urapplications o k response has a 2xx status code
func (o *PostAPIUrapplicationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api urapplications o k response has a 3xx status code
func (o *PostAPIUrapplicationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api urapplications o k response has a 4xx status code
func (o *PostAPIUrapplicationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api urapplications o k response has a 5xx status code
func (o *PostAPIUrapplicationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api urapplications o k response a status code equal to that given
func (o *PostAPIUrapplicationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api urapplications o k response
func (o *PostAPIUrapplicationsOK) Code() int {
	return 200
}

func (o *PostAPIUrapplicationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/urapplications][%d] postApiUrapplicationsOK %s", 200, payload)
}

func (o *PostAPIUrapplicationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/urapplications][%d] postApiUrapplicationsOK %s", 200, payload)
}

func (o *PostAPIUrapplicationsOK) GetPayload() *models.APIURCreateApplicationResponse {
	return o.Payload
}

func (o *PostAPIUrapplicationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIURCreateApplicationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
