// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIUrapplicationsIntegrationsHTTPByIDParams creates a new PostAPIUrapplicationsIntegrationsHTTPByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIUrapplicationsIntegrationsHTTPByIDParams() *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	return &PostAPIUrapplicationsIntegrationsHTTPByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithTimeout creates a new PostAPIUrapplicationsIntegrationsHTTPByIDParams object
// with the ability to set a timeout on a request.
func NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithTimeout(timeout time.Duration) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	return &PostAPIUrapplicationsIntegrationsHTTPByIDParams{
		timeout: timeout,
	}
}

// NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithContext creates a new PostAPIUrapplicationsIntegrationsHTTPByIDParams object
// with the ability to set a context for a request.
func NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithContext(ctx context.Context) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	return &PostAPIUrapplicationsIntegrationsHTTPByIDParams{
		Context: ctx,
	}
}

// NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithHTTPClient creates a new PostAPIUrapplicationsIntegrationsHTTPByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIUrapplicationsIntegrationsHTTPByIDParamsWithHTTPClient(client *http.Client) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	return &PostAPIUrapplicationsIntegrationsHTTPByIDParams{
		HTTPClient: client,
	}
}

/*
PostAPIUrapplicationsIntegrationsHTTPByIDParams contains all the parameters to send to the API endpoint

	for the post api urapplications integrations http by id operation.

	Typically these are written to a http.Request.
*/
type PostAPIUrapplicationsIntegrationsHTTPByIDParams struct {

	// Body.
	Body *models.APIURHTTPIntegration

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api urapplications integrations http by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithDefaults() *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api urapplications integrations http by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithTimeout(timeout time.Duration) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithContext(ctx context.Context) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithHTTPClient(client *http.Client) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithBody(body *models.APIURHTTPIntegration) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetBody(body *models.APIURHTTPIntegration) {
	o.Body = body
}

// WithID adds the id to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WithID(id string) *PostAPIUrapplicationsIntegrationsHTTPByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post api urapplications integrations http by id params
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIUrapplicationsIntegrationsHTTPByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
