// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIUrapplicationsIntegrationsMqttByIDReader is a Reader for the PostAPIUrapplicationsIntegrationsMqttByID structure.
type PostAPIUrapplicationsIntegrationsMqttByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIUrapplicationsIntegrationsMqttByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIUrapplicationsIntegrationsMqttByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/urapplications/{id}/integrations/mqtt] post_api_urapplications_integrations_mqtt_by_id", response, response.Code())
	}
}

// NewPostAPIUrapplicationsIntegrationsMqttByIDOK creates a PostAPIUrapplicationsIntegrationsMqttByIDOK with default headers values
func NewPostAPIUrapplicationsIntegrationsMqttByIDOK() *PostAPIUrapplicationsIntegrationsMqttByIDOK {
	return &PostAPIUrapplicationsIntegrationsMqttByIDOK{}
}

/*
PostAPIUrapplicationsIntegrationsMqttByIDOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIUrapplicationsIntegrationsMqttByIDOK struct {
	Payload models.APIUREmptyResponse
}

// IsSuccess returns true when this post Api urapplications integrations mqtt by Id o k response has a 2xx status code
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api urapplications integrations mqtt by Id o k response has a 3xx status code
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api urapplications integrations mqtt by Id o k response has a 4xx status code
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api urapplications integrations mqtt by Id o k response has a 5xx status code
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api urapplications integrations mqtt by Id o k response a status code equal to that given
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api urapplications integrations mqtt by Id o k response
func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) Code() int {
	return 200
}

func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/urapplications/{id}/integrations/mqtt][%d] postApiUrapplicationsIntegrationsMqttByIdOK %s", 200, payload)
}

func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/urapplications/{id}/integrations/mqtt][%d] postApiUrapplicationsIntegrationsMqttByIdOK %s", 200, payload)
}

func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) GetPayload() models.APIUREmptyResponse {
	return o.Payload
}

func (o *PostAPIUrapplicationsIntegrationsMqttByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
