// Code generated by go-swagger; DO NOT EDIT.

package ursalink_application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIUrapplicationsIntegrationsMqttByIDParams creates a new PutAPIUrapplicationsIntegrationsMqttByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIUrapplicationsIntegrationsMqttByIDParams() *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	return &PutAPIUrapplicationsIntegrationsMqttByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithTimeout creates a new PutAPIUrapplicationsIntegrationsMqttByIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithTimeout(timeout time.Duration) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	return &PutAPIUrapplicationsIntegrationsMqttByIDParams{
		timeout: timeout,
	}
}

// NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithContext creates a new PutAPIUrapplicationsIntegrationsMqttByIDParams object
// with the ability to set a context for a request.
func NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithContext(ctx context.Context) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	return &PutAPIUrapplicationsIntegrationsMqttByIDParams{
		Context: ctx,
	}
}

// NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithHTTPClient creates a new PutAPIUrapplicationsIntegrationsMqttByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIUrapplicationsIntegrationsMqttByIDParamsWithHTTPClient(client *http.Client) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	return &PutAPIUrapplicationsIntegrationsMqttByIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIUrapplicationsIntegrationsMqttByIDParams contains all the parameters to send to the API endpoint

	for the put api urapplications integrations mqtt by id operation.

	Typically these are written to a http.Request.
*/
type PutAPIUrapplicationsIntegrationsMqttByIDParams struct {

	// Body.
	Body *models.APIURMQTTIntegration

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put api urapplications integrations mqtt by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithDefaults() *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put api urapplications integrations mqtt by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithTimeout(timeout time.Duration) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithContext(ctx context.Context) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithHTTPClient(client *http.Client) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithBody(body *models.APIURMQTTIntegration) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetBody(body *models.APIURMQTTIntegration) {
	o.Body = body
}

// WithID adds the id to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WithID(id string) *PutAPIUrapplicationsIntegrationsMqttByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put api urapplications integrations mqtt by id params
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIUrapplicationsIntegrationsMqttByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
