// Code generated by go-swagger; DO NOT EDIT.

package gateway_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams creates a new PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams() *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	return &PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithTimeout creates a new PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithTimeout(timeout time.Duration) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	return &PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams{
		timeout: timeout,
	}
}

// NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithContext creates a new PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams object
// with the ability to set a context for a request.
func NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithContext(ctx context.Context) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	return &PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams{
		Context: ctx,
	}
}

// NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithHTTPClient creates a new PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParamsWithHTTPClient(client *http.Client) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	return &PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams contains all the parameters to send to the API endpoint

	for the put api gateway profiles by gateway profile gateway profile ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams struct {

	// Body.
	Body *models.APIUpdateGatewayProfileRequest

	/* GatewayProfileGatewayProfileID.

	   ID of the gateway-profile.
	*/
	GatewayProfileGatewayProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put api gateway profiles by gateway profile gateway profile ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithDefaults() *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put api gateway profiles by gateway profile gateway profile ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithTimeout(timeout time.Duration) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithContext(ctx context.Context) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithHTTPClient(client *http.Client) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithBody(body *models.APIUpdateGatewayProfileRequest) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetBody(body *models.APIUpdateGatewayProfileRequest) {
	o.Body = body
}

// WithGatewayProfileGatewayProfileID adds the gatewayProfileGatewayProfileID to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WithGatewayProfileGatewayProfileID(gatewayProfileGatewayProfileID string) *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams {
	o.SetGatewayProfileGatewayProfileID(gatewayProfileGatewayProfileID)
	return o
}

// SetGatewayProfileGatewayProfileID adds the gatewayProfileGatewayProfileId to the put api gateway profiles by gateway profile gateway profile ID params
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) SetGatewayProfileGatewayProfileID(gatewayProfileGatewayProfileID string) {
	o.GatewayProfileGatewayProfileID = gatewayProfileGatewayProfileID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIGatewayProfilesByGatewayProfileGatewayProfileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param gatewayProfile.gatewayProfileID
	if err := r.SetPathParam("gatewayProfile.gatewayProfileID", o.GatewayProfileGatewayProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
