// Code generated by go-swagger; DO NOT EDIT.

package ursalink_user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllAppsParams creates a new ListAllAppsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListAllAppsParams() *ListAllAppsParams {
	return &ListAllAppsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListAllAppsParamsWithTimeout creates a new ListAllAppsParams object
// with the ability to set a timeout on a request.
func NewListAllAppsParamsWithTimeout(timeout time.Duration) *ListAllAppsParams {
	return &ListAllAppsParams{
		timeout: timeout,
	}
}

// NewListAllAppsParamsWithContext creates a new ListAllAppsParams object
// with the ability to set a context for a request.
func NewListAllAppsParamsWithContext(ctx context.Context) *ListAllAppsParams {
	return &ListAllAppsParams{
		Context: ctx,
	}
}

// NewListAllAppsParamsWithHTTPClient creates a new ListAllAppsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListAllAppsParamsWithHTTPClient(client *http.Client) *ListAllAppsParams {
	return &ListAllAppsParams{
		HTTPClient: client,
	}
}

/*
ListAllAppsParams contains all the parameters to send to the API endpoint

	for the list all apps operation.

	Typically these are written to a http.Request.
*/
type ListAllAppsParams struct {

	/* Limit.

	   Max number of applications to return in the apps-test.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset in the apps-set (for pagination).

	   Format: int64
	*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list all apps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllAppsParams) WithDefaults() *ListAllAppsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list all apps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllAppsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list all apps params
func (o *ListAllAppsParams) WithTimeout(timeout time.Duration) *ListAllAppsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all apps params
func (o *ListAllAppsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all apps params
func (o *ListAllAppsParams) WithContext(ctx context.Context) *ListAllAppsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all apps params
func (o *ListAllAppsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all apps params
func (o *ListAllAppsParams) WithHTTPClient(client *http.Client) *ListAllAppsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all apps params
func (o *ListAllAppsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the list all apps params
func (o *ListAllAppsParams) WithLimit(limit *string) *ListAllAppsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list all apps params
func (o *ListAllAppsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the list all apps params
func (o *ListAllAppsParams) WithOffset(offset *string) *ListAllAppsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list all apps params
func (o *ListAllAppsParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllAppsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
