// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParams creates a new GetAPIProtocolModbusServerNetworkInterfacesOptionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParams() *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	return &GetAPIProtocolModbusServerNetworkInterfacesOptionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithTimeout creates a new GetAPIProtocolModbusServerNetworkInterfacesOptionsParams object
// with the ability to set a timeout on a request.
func NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithTimeout(timeout time.Duration) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	return &GetAPIProtocolModbusServerNetworkInterfacesOptionsParams{
		timeout: timeout,
	}
}

// NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithContext creates a new GetAPIProtocolModbusServerNetworkInterfacesOptionsParams object
// with the ability to set a context for a request.
func NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithContext(ctx context.Context) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	return &GetAPIProtocolModbusServerNetworkInterfacesOptionsParams{
		Context: ctx,
	}
}

// NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithHTTPClient creates a new GetAPIProtocolModbusServerNetworkInterfacesOptionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIProtocolModbusServerNetworkInterfacesOptionsParamsWithHTTPClient(client *http.Client) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	return &GetAPIProtocolModbusServerNetworkInterfacesOptionsParams{
		HTTPClient: client,
	}
}

/*
GetAPIProtocolModbusServerNetworkInterfacesOptionsParams contains all the parameters to send to the API endpoint

	for the get api protocol modbus server network interfaces options operation.

	Typically these are written to a http.Request.
*/
type GetAPIProtocolModbusServerNetworkInterfacesOptionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get api protocol modbus server network interfaces options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) WithDefaults() *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get api protocol modbus server network interfaces options params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) WithTimeout(timeout time.Duration) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) WithContext(ctx context.Context) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) WithHTTPClient(client *http.Client) *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get api protocol modbus server network interfaces options params
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIProtocolModbusServerNetworkInterfacesOptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
