// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAllReader is a Reader for the GetAll structure.
type GetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/protocol/modbus_object/getall] GetAll", response, response.Code())
	}
}

// NewGetAllOK creates a GetAllOK with default headers values
func NewGetAllOK() *GetAllOK {
	return &GetAllOK{}
}

/*
GetAllOK describes a response with status code 200, with default header values.

GetAllOK get all o k
*/
type GetAllOK struct {
	Payload *models.APIGetModbusObjectResponse
}

// IsSuccess returns true when this get all o k response has a 2xx status code
func (o *GetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all o k response has a 3xx status code
func (o *GetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all o k response has a 4xx status code
func (o *GetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all o k response has a 5xx status code
func (o *GetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all o k response a status code equal to that given
func (o *GetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all o k response
func (o *GetAllOK) Code() int {
	return 200
}

func (o *GetAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/protocol/modbus_object/getall][%d] getAllOK %s", 200, payload)
}

func (o *GetAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/protocol/modbus_object/getall][%d] getAllOK %s", 200, payload)
}

func (o *GetAllOK) GetPayload() *models.APIGetModbusObjectResponse {
	return o.Payload
}

func (o *GetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetModbusObjectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
