// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIProtocolModbusObjectDeleteParams creates a new PostAPIProtocolModbusObjectDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIProtocolModbusObjectDeleteParams() *PostAPIProtocolModbusObjectDeleteParams {
	return &PostAPIProtocolModbusObjectDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIProtocolModbusObjectDeleteParamsWithTimeout creates a new PostAPIProtocolModbusObjectDeleteParams object
// with the ability to set a timeout on a request.
func NewPostAPIProtocolModbusObjectDeleteParamsWithTimeout(timeout time.Duration) *PostAPIProtocolModbusObjectDeleteParams {
	return &PostAPIProtocolModbusObjectDeleteParams{
		timeout: timeout,
	}
}

// NewPostAPIProtocolModbusObjectDeleteParamsWithContext creates a new PostAPIProtocolModbusObjectDeleteParams object
// with the ability to set a context for a request.
func NewPostAPIProtocolModbusObjectDeleteParamsWithContext(ctx context.Context) *PostAPIProtocolModbusObjectDeleteParams {
	return &PostAPIProtocolModbusObjectDeleteParams{
		Context: ctx,
	}
}

// NewPostAPIProtocolModbusObjectDeleteParamsWithHTTPClient creates a new PostAPIProtocolModbusObjectDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIProtocolModbusObjectDeleteParamsWithHTTPClient(client *http.Client) *PostAPIProtocolModbusObjectDeleteParams {
	return &PostAPIProtocolModbusObjectDeleteParams{
		HTTPClient: client,
	}
}

/*
PostAPIProtocolModbusObjectDeleteParams contains all the parameters to send to the API endpoint

	for the post api protocol modbus object delete operation.

	Typically these are written to a http.Request.
*/
type PostAPIProtocolModbusObjectDeleteParams struct {

	// Body.
	Body *models.APIDeleteModbusObjectRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api protocol modbus object delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusObjectDeleteParams) WithDefaults() *PostAPIProtocolModbusObjectDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api protocol modbus object delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusObjectDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) WithTimeout(timeout time.Duration) *PostAPIProtocolModbusObjectDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) WithContext(ctx context.Context) *PostAPIProtocolModbusObjectDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) WithHTTPClient(client *http.Client) *PostAPIProtocolModbusObjectDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) WithBody(body *models.APIDeleteModbusObjectRequest) *PostAPIProtocolModbusObjectDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api protocol modbus object delete params
func (o *PostAPIProtocolModbusObjectDeleteParams) SetBody(body *models.APIDeleteModbusObjectRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIProtocolModbusObjectDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
