// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIProtocolModbusObjectGetDevicesOfSameTypeReader is a Reader for the PostAPIProtocolModbusObjectGetDevicesOfSameType structure.
type PostAPIProtocolModbusObjectGetDevicesOfSameTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIProtocolModbusObjectGetDevicesOfSameTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/protocol/modbus_object/get_devices_of_same_type] post_api_protocol_modbus_object_get_devices_of_same_type", response, response.Code())
	}
}

// NewPostAPIProtocolModbusObjectGetDevicesOfSameTypeOK creates a PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK with default headers values
func NewPostAPIProtocolModbusObjectGetDevicesOfSameTypeOK() *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK {
	return &PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK{}
}

/*
PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK struct {
	Payload *models.APIGetDevicesOfSameTypeResponse
}

// IsSuccess returns true when this post Api protocol modbus object get devices of same type o k response has a 2xx status code
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api protocol modbus object get devices of same type o k response has a 3xx status code
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api protocol modbus object get devices of same type o k response has a 4xx status code
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api protocol modbus object get devices of same type o k response has a 5xx status code
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api protocol modbus object get devices of same type o k response a status code equal to that given
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api protocol modbus object get devices of same type o k response
func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) Code() int {
	return 200
}

func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/protocol/modbus_object/get_devices_of_same_type][%d] postApiProtocolModbusObjectGetDevicesOfSameTypeOK %s", 200, payload)
}

func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/protocol/modbus_object/get_devices_of_same_type][%d] postApiProtocolModbusObjectGetDevicesOfSameTypeOK %s", 200, payload)
}

func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) GetPayload() *models.APIGetDevicesOfSameTypeResponse {
	return o.Payload
}

func (o *PostAPIProtocolModbusObjectGetDevicesOfSameTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetDevicesOfSameTypeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
