// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIProtocolModbusDeviceDeleteParams creates a new PostAPIProtocolModbusDeviceDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIProtocolModbusDeviceDeleteParams() *PostAPIProtocolModbusDeviceDeleteParams {
	return &PostAPIProtocolModbusDeviceDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIProtocolModbusDeviceDeleteParamsWithTimeout creates a new PostAPIProtocolModbusDeviceDeleteParams object
// with the ability to set a timeout on a request.
func NewPostAPIProtocolModbusDeviceDeleteParamsWithTimeout(timeout time.Duration) *PostAPIProtocolModbusDeviceDeleteParams {
	return &PostAPIProtocolModbusDeviceDeleteParams{
		timeout: timeout,
	}
}

// NewPostAPIProtocolModbusDeviceDeleteParamsWithContext creates a new PostAPIProtocolModbusDeviceDeleteParams object
// with the ability to set a context for a request.
func NewPostAPIProtocolModbusDeviceDeleteParamsWithContext(ctx context.Context) *PostAPIProtocolModbusDeviceDeleteParams {
	return &PostAPIProtocolModbusDeviceDeleteParams{
		Context: ctx,
	}
}

// NewPostAPIProtocolModbusDeviceDeleteParamsWithHTTPClient creates a new PostAPIProtocolModbusDeviceDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIProtocolModbusDeviceDeleteParamsWithHTTPClient(client *http.Client) *PostAPIProtocolModbusDeviceDeleteParams {
	return &PostAPIProtocolModbusDeviceDeleteParams{
		HTTPClient: client,
	}
}

/*
PostAPIProtocolModbusDeviceDeleteParams contains all the parameters to send to the API endpoint

	for the post api protocol modbus device delete operation.

	Typically these are written to a http.Request.
*/
type PostAPIProtocolModbusDeviceDeleteParams struct {

	// Body.
	Body *models.APIDeleteModbusDeviceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api protocol modbus device delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusDeviceDeleteParams) WithDefaults() *PostAPIProtocolModbusDeviceDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api protocol modbus device delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusDeviceDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) WithTimeout(timeout time.Duration) *PostAPIProtocolModbusDeviceDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) WithContext(ctx context.Context) *PostAPIProtocolModbusDeviceDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) WithHTTPClient(client *http.Client) *PostAPIProtocolModbusDeviceDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) WithBody(body *models.APIDeleteModbusDeviceRequest) *PostAPIProtocolModbusDeviceDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api protocol modbus device delete params
func (o *PostAPIProtocolModbusDeviceDeleteParams) SetBody(body *models.APIDeleteModbusDeviceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIProtocolModbusDeviceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
