// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIProtocolModbusObjectExportParams creates a new PostAPIProtocolModbusObjectExportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIProtocolModbusObjectExportParams() *PostAPIProtocolModbusObjectExportParams {
	return &PostAPIProtocolModbusObjectExportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIProtocolModbusObjectExportParamsWithTimeout creates a new PostAPIProtocolModbusObjectExportParams object
// with the ability to set a timeout on a request.
func NewPostAPIProtocolModbusObjectExportParamsWithTimeout(timeout time.Duration) *PostAPIProtocolModbusObjectExportParams {
	return &PostAPIProtocolModbusObjectExportParams{
		timeout: timeout,
	}
}

// NewPostAPIProtocolModbusObjectExportParamsWithContext creates a new PostAPIProtocolModbusObjectExportParams object
// with the ability to set a context for a request.
func NewPostAPIProtocolModbusObjectExportParamsWithContext(ctx context.Context) *PostAPIProtocolModbusObjectExportParams {
	return &PostAPIProtocolModbusObjectExportParams{
		Context: ctx,
	}
}

// NewPostAPIProtocolModbusObjectExportParamsWithHTTPClient creates a new PostAPIProtocolModbusObjectExportParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIProtocolModbusObjectExportParamsWithHTTPClient(client *http.Client) *PostAPIProtocolModbusObjectExportParams {
	return &PostAPIProtocolModbusObjectExportParams{
		HTTPClient: client,
	}
}

/*
PostAPIProtocolModbusObjectExportParams contains all the parameters to send to the API endpoint

	for the post api protocol modbus object export operation.

	Typically these are written to a http.Request.
*/
type PostAPIProtocolModbusObjectExportParams struct {

	// Body.
	Body *models.APIExportModbusObjectRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api protocol modbus object export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusObjectExportParams) WithDefaults() *PostAPIProtocolModbusObjectExportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api protocol modbus object export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIProtocolModbusObjectExportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) WithTimeout(timeout time.Duration) *PostAPIProtocolModbusObjectExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) WithContext(ctx context.Context) *PostAPIProtocolModbusObjectExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) WithHTTPClient(client *http.Client) *PostAPIProtocolModbusObjectExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) WithBody(body *models.APIExportModbusObjectRequest) *PostAPIProtocolModbusObjectExportParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api protocol modbus object export params
func (o *PostAPIProtocolModbusObjectExportParams) SetBody(body *models.APIExportModbusObjectRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIProtocolModbusObjectExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
