// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIProtocolModbusDeviceParams creates a new PutAPIProtocolModbusDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIProtocolModbusDeviceParams() *PutAPIProtocolModbusDeviceParams {
	return &PutAPIProtocolModbusDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIProtocolModbusDeviceParamsWithTimeout creates a new PutAPIProtocolModbusDeviceParams object
// with the ability to set a timeout on a request.
func NewPutAPIProtocolModbusDeviceParamsWithTimeout(timeout time.Duration) *PutAPIProtocolModbusDeviceParams {
	return &PutAPIProtocolModbusDeviceParams{
		timeout: timeout,
	}
}

// NewPutAPIProtocolModbusDeviceParamsWithContext creates a new PutAPIProtocolModbusDeviceParams object
// with the ability to set a context for a request.
func NewPutAPIProtocolModbusDeviceParamsWithContext(ctx context.Context) *PutAPIProtocolModbusDeviceParams {
	return &PutAPIProtocolModbusDeviceParams{
		Context: ctx,
	}
}

// NewPutAPIProtocolModbusDeviceParamsWithHTTPClient creates a new PutAPIProtocolModbusDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIProtocolModbusDeviceParamsWithHTTPClient(client *http.Client) *PutAPIProtocolModbusDeviceParams {
	return &PutAPIProtocolModbusDeviceParams{
		HTTPClient: client,
	}
}

/*
PutAPIProtocolModbusDeviceParams contains all the parameters to send to the API endpoint

	for the put api protocol modbus device operation.

	Typically these are written to a http.Request.
*/
type PutAPIProtocolModbusDeviceParams struct {

	// Body.
	Body *models.APIUpdateModbusDeviceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put api protocol modbus device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIProtocolModbusDeviceParams) WithDefaults() *PutAPIProtocolModbusDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put api protocol modbus device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIProtocolModbusDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) WithTimeout(timeout time.Duration) *PutAPIProtocolModbusDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) WithContext(ctx context.Context) *PutAPIProtocolModbusDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) WithHTTPClient(client *http.Client) *PutAPIProtocolModbusDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) WithBody(body *models.APIUpdateModbusDeviceRequest) *PutAPIProtocolModbusDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put api protocol modbus device params
func (o *PutAPIProtocolModbusDeviceParams) SetBody(body *models.APIUpdateModbusDeviceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIProtocolModbusDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
