// Code generated by go-swagger; DO NOT EDIT.

package modbus_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PutAPIProtocolModbusDeviceReader is a Reader for the PutAPIProtocolModbusDevice structure.
type PutAPIProtocolModbusDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIProtocolModbusDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIProtocolModbusDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/protocol/modbus_device] put_api_protocol_modbus_device", response, response.Code())
	}
}

// NewPutAPIProtocolModbusDeviceOK creates a PutAPIProtocolModbusDeviceOK with default headers values
func NewPutAPIProtocolModbusDeviceOK() *PutAPIProtocolModbusDeviceOK {
	return &PutAPIProtocolModbusDeviceOK{}
}

/*
PutAPIProtocolModbusDeviceOK describes a response with status code 200, with default header values.

(empty)
*/
type PutAPIProtocolModbusDeviceOK struct {
	Payload *models.APIStandardRes
}

// IsSuccess returns true when this put Api protocol modbus device o k response has a 2xx status code
func (o *PutAPIProtocolModbusDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api protocol modbus device o k response has a 3xx status code
func (o *PutAPIProtocolModbusDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api protocol modbus device o k response has a 4xx status code
func (o *PutAPIProtocolModbusDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api protocol modbus device o k response has a 5xx status code
func (o *PutAPIProtocolModbusDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api protocol modbus device o k response a status code equal to that given
func (o *PutAPIProtocolModbusDeviceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api protocol modbus device o k response
func (o *PutAPIProtocolModbusDeviceOK) Code() int {
	return 200
}

func (o *PutAPIProtocolModbusDeviceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/protocol/modbus_device][%d] putApiProtocolModbusDeviceOK %s", 200, payload)
}

func (o *PutAPIProtocolModbusDeviceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/protocol/modbus_device][%d] putApiProtocolModbusDeviceOK %s", 200, payload)
}

func (o *PutAPIProtocolModbusDeviceOK) GetPayload() *models.APIStandardRes {
	return o.Payload
}

func (o *PutAPIProtocolModbusDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIStandardRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
