// Code generated by go-swagger; DO NOT EDIT.

package ursalink_packets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// DeleteAPIUrpacketsQueueitemsReader is a Reader for the DeleteAPIUrpacketsQueueitems structure.
type DeleteAPIUrpacketsQueueitemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIUrpacketsQueueitemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIUrpacketsQueueitemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/urpackets/queueitems] delete_api_urpackets_queueitems", response, response.Code())
	}
}

// NewDeleteAPIUrpacketsQueueitemsOK creates a DeleteAPIUrpacketsQueueitemsOK with default headers values
func NewDeleteAPIUrpacketsQueueitemsOK() *DeleteAPIUrpacketsQueueitemsOK {
	return &DeleteAPIUrpacketsQueueitemsOK{}
}

/*
DeleteAPIUrpacketsQueueitemsOK describes a response with status code 200, with default header values.

(empty)
*/
type DeleteAPIUrpacketsQueueitemsOK struct {
	Payload models.APICleanAllQueueItemsResponse
}

// IsSuccess returns true when this delete Api urpackets queueitems o k response has a 2xx status code
func (o *DeleteAPIUrpacketsQueueitemsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api urpackets queueitems o k response has a 3xx status code
func (o *DeleteAPIUrpacketsQueueitemsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api urpackets queueitems o k response has a 4xx status code
func (o *DeleteAPIUrpacketsQueueitemsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api urpackets queueitems o k response has a 5xx status code
func (o *DeleteAPIUrpacketsQueueitemsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api urpackets queueitems o k response a status code equal to that given
func (o *DeleteAPIUrpacketsQueueitemsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api urpackets queueitems o k response
func (o *DeleteAPIUrpacketsQueueitemsOK) Code() int {
	return 200
}

func (o *DeleteAPIUrpacketsQueueitemsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/urpackets/queueitems][%d] deleteApiUrpacketsQueueitemsOK %s", 200, payload)
}

func (o *DeleteAPIUrpacketsQueueitemsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/urpackets/queueitems][%d] deleteApiUrpacketsQueueitemsOK %s", 200, payload)
}

func (o *DeleteAPIUrpacketsQueueitemsOK) GetPayload() models.APICleanAllQueueItemsResponse {
	return o.Payload
}

func (o *DeleteAPIUrpacketsQueueitemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
