// Code generated by go-swagger; DO NOT EDIT.

package device_queue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// FlushReader is a Reader for the Flush structure.
type FlushReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FlushReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFlushOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/devices/{devEUI}/queue] Flush", response, response.Code())
	}
}

// NewFlushOK creates a FlushOK with default headers values
func NewFlushOK() *FlushOK {
	return &FlushOK{}
}

/*
FlushOK describes a response with status code 200, with default header values.

FlushOK flush o k
*/
type FlushOK struct {
	Payload models.APIFlushDeviceQueueResponse
}

// IsSuccess returns true when this flush o k response has a 2xx status code
func (o *FlushOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this flush o k response has a 3xx status code
func (o *FlushOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this flush o k response has a 4xx status code
func (o *FlushOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this flush o k response has a 5xx status code
func (o *FlushOK) IsServerError() bool {
	return false
}

// IsCode returns true when this flush o k response a status code equal to that given
func (o *FlushOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the flush o k response
func (o *FlushOK) Code() int {
	return 200
}

func (o *FlushOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/devices/{devEUI}/queue][%d] flushOK %s", 200, payload)
}

func (o *FlushOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/devices/{devEUI}/queue][%d] flushOK %s", 200, payload)
}

func (o *FlushOK) GetPayload() models.APIFlushDeviceQueueResponse {
	return o.Payload
}

func (o *FlushOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
