[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level = 4

channel_plan = "CN470"

use_dynamic_payload = true

# ChirpStack configuration.
[chirpstack]

# API configuration.
#
# This configuration is used to automatically create the:
#   * Device profile
#   * Gateways
#   * Application
#   * Devices
[chirpstack.api]

# API key.
#
# The API key can be obtained through the ChirpStack web-interface.
api_key = ""

# Server.
#
# This must point to the ChirpStack API interface.
server = "http://192.168.40.147"

# 网关as api登录url
login_url = "/api/internal/login"
# 网关as api登录用户名
username = "admin"
# 网关as api登录密码
password = "password"
# 是否是devicehubv2 LNS
is_lns = false
# devicehubv2 LNS配置
use_new_gateway = false
# 暂时无用
use_new_profile = false
# 是否每次创建新的application
use_new_app = true
# 是否使用旧版校验方式(60.0.0.42-r5前的网关)
use_old_auth = false
# 是否每次创建新的application
clean_before_test = true
# 结束后是否删除所有数据
teardown_after_test = false
# 测试的功能，目前支持bacnet，fuota，normal
test_feature = "fuota"

# 是否使用TLS
# Insecure.
#
# Set this to true when the endpoint is not using TLS.
insecure = true

# MQTT integration configuration.
#
# This integration is used for counting the number of uplinks that are
# published by the ChirpStack MQTT integration.
[chirpstack.integration.mqtt]

# MQTT server.
server = "tcp://192.168.40.147:1883"

ssh_password = ""

# Username.
username = "lorawan"

# Password.
password = "Urs@L1nk#Ms2020"


# MQTT gateway backend.
[chirpstack.gateway.backend.mqtt]

# MQTT server.
server = "tcp://192.168.40.147:1883"

# Username.
username = "lorawan"

# Password.
password = "Urs@L1nk#Ms2020"


# Simulator configuration.
#
# Example:
[[simulator]]

# Tenant ID.
#
# It is recommended to create a new tenant in ChirpStack.
tenant_id = "f6f7d81d-647f-4c7f-8409-3e5218c0c523"

# Duration.
#
# This defines the duration of the simulation. If set to '0s', the simulation
# will run until terminated. This includes the activation time.
duration = "0s"

# Activation time.
#
# This is the time that the simulator takes to activate the devices. This
# value must be less than the simulator duration.
activation_time = "10s"

# Device configuration.
[simulator.device]

# Number of devices to simulate.
count = 1

# Uplink interval.
uplink_interval = "60s"

# FPort.
f_port = 1

# Payload (HEX encoded).
payload = "010203"

# Frequency (Hz).
frequency = 471900000

# Bandwidth (Hz).
bandwidth = 125000

# Spreading-factor.
spreading_factor = 7

# Gateway configuration.
[simulator.gateway]

# Event topic template.
event_topic_template = "gateway/{{ .GatewayID }}/rx"

# Command topic template.
command_topic_template = "gateway/{{ .GatewayID }}/tx"

# Min number of receiving gateways.
min_count = 3

# Max number of receiving gateways.
max_count = 5


# Prometheus metrics configuration.
#
# Using Prometheus (and Grafana), it is possible to visualize various
# simulation metrics like:
#   * Join-Requests sent
#   * Join-Accepts received
#   * Uplinks sent (by the devices)
#   * Uplinks sent (by the gateways)
#   * Uplinks sent (by the ChirpStack Application Server MQTT integration)
[prometheus]

# IP:port to bind the Prometheus endpoint to.
#
# Metrics can be retrieved from /metrics.
bind = "0.0.0.0:9000"
