// Code generated by go-swagger; DO NOT EDIT.

package device_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new device profile service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new device profile service API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new device profile service API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for device profile service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPIDeviceProfilesByDeviceProfileID(params *DeleteAPIDeviceProfilesByDeviceProfileIDParams, opts ...ClientOption) (*DeleteAPIDeviceProfilesByDeviceProfileIDOK, error)

	GetAPIDeviceProfiles(params *GetAPIDeviceProfilesParams, opts ...ClientOption) (*GetAPIDeviceProfilesOK, error)

	GetAPIDeviceProfilesByDeviceProfileID(params *GetAPIDeviceProfilesByDeviceProfileIDParams, opts ...ClientOption) (*GetAPIDeviceProfilesByDeviceProfileIDOK, error)

	PostAPIDeviceProfiles(params *PostAPIDeviceProfilesParams, opts ...ClientOption) (*PostAPIDeviceProfilesOK, error)

	PutAPIDeviceProfilesByDeviceProfileDeviceProfileID(params *PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDParams, opts ...ClientOption) (*PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPIDeviceProfilesByDeviceProfileID deletes deletes the device profile matching the given id
*/
func (a *Client) DeleteAPIDeviceProfilesByDeviceProfileID(params *DeleteAPIDeviceProfilesByDeviceProfileIDParams, opts ...ClientOption) (*DeleteAPIDeviceProfilesByDeviceProfileIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAPIDeviceProfilesByDeviceProfileIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete_api_device-profiles_by_deviceProfileID",
		Method:             "DELETE",
		PathPattern:        "/api/device-profiles/{deviceProfileID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteAPIDeviceProfilesByDeviceProfileIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteAPIDeviceProfilesByDeviceProfileIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete_api_device-profiles_by_deviceProfileID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIDeviceProfiles lists lists the available device profiles
*/
func (a *Client) GetAPIDeviceProfiles(params *GetAPIDeviceProfilesParams, opts ...ClientOption) (*GetAPIDeviceProfilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIDeviceProfilesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_device-profiles",
		Method:             "GET",
		PathPattern:        "/api/device-profiles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPIDeviceProfilesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIDeviceProfilesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_device-profiles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIDeviceProfilesByDeviceProfileID gets returns the device profile matching the given id
*/
func (a *Client) GetAPIDeviceProfilesByDeviceProfileID(params *GetAPIDeviceProfilesByDeviceProfileIDParams, opts ...ClientOption) (*GetAPIDeviceProfilesByDeviceProfileIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIDeviceProfilesByDeviceProfileIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_device-profiles_by_deviceProfileID",
		Method:             "GET",
		PathPattern:        "/api/device-profiles/{deviceProfileID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPIDeviceProfilesByDeviceProfileIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIDeviceProfilesByDeviceProfileIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_device-profiles_by_deviceProfileID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIDeviceProfiles creates creates the given device profile
*/
func (a *Client) PostAPIDeviceProfiles(params *PostAPIDeviceProfilesParams, opts ...ClientOption) (*PostAPIDeviceProfilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAPIDeviceProfilesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "post_api_device-profiles",
		Method:             "POST",
		PathPattern:        "/api/device-profiles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostAPIDeviceProfilesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAPIDeviceProfilesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post_api_device-profiles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIDeviceProfilesByDeviceProfileDeviceProfileID updates updates the given device profile
*/
func (a *Client) PutAPIDeviceProfilesByDeviceProfileDeviceProfileID(params *PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDParams, opts ...ClientOption) (*PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPIDeviceProfilesByDeviceProfileDeviceProfileIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "put_api_device-profiles_by_deviceProfile.deviceProfileID",
		Method:             "PUT",
		PathPattern:        "/api/device-profiles/{deviceProfile.deviceProfileID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutAPIDeviceProfilesByDeviceProfileDeviceProfileIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for put_api_device-profiles_by_deviceProfile.deviceProfileID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
