// Code generated by go-swagger; DO NOT EDIT.

package device_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams creates a new PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams() *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	return &PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithTimeout creates a new PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithTimeout(timeout time.Duration) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	return &PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams{
		timeout: timeout,
	}
}

// NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithContext creates a new PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams object
// with the ability to set a context for a request.
func NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithContext(ctx context.Context) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	return &PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams{
		Context: ctx,
	}
}

// NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithHTTPClient creates a new PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIDeviceProfilesDeviceProfileDeviceProfileIDParamsWithHTTPClient(client *http.Client) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	return &PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams contains all the parameters to send to the API endpoint

	for the put API device profiles device profile device profile ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams struct {

	// Body.
	Body *models.APIUpdateDeviceProfileRequest

	// DeviceProfileDeviceProfileID.
	DeviceProfileDeviceProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API device profiles device profile device profile ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithDefaults() *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API device profiles device profile device profile ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithTimeout(timeout time.Duration) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithContext(ctx context.Context) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithHTTPClient(client *http.Client) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithBody(body *models.APIUpdateDeviceProfileRequest) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetBody(body *models.APIUpdateDeviceProfileRequest) {
	o.Body = body
}

// WithDeviceProfileDeviceProfileID adds the deviceProfileDeviceProfileID to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WithDeviceProfileDeviceProfileID(deviceProfileDeviceProfileID string) *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams {
	o.SetDeviceProfileDeviceProfileID(deviceProfileDeviceProfileID)
	return o
}

// SetDeviceProfileDeviceProfileID adds the deviceProfileDeviceProfileId to the put API device profiles device profile device profile ID params
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) SetDeviceProfileDeviceProfileID(deviceProfileDeviceProfileID string) {
	o.DeviceProfileDeviceProfileID = deviceProfileDeviceProfileID
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIDeviceProfilesDeviceProfileDeviceProfileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param deviceProfile.deviceProfileID
	if err := r.SetPathParam("deviceProfile.deviceProfileID", o.DeviceProfileDeviceProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
