// Code generated by go-swagger; DO NOT EDIT.

package ursalink_profiles_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListParams creates a new ListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListParams() *ListParams {
	return &ListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListParamsWithTimeout creates a new ListParams object
// with the ability to set a timeout on a request.
func NewListParamsWithTimeout(timeout time.Duration) *ListParams {
	return &ListParams{
		timeout: timeout,
	}
}

// NewListParamsWithContext creates a new ListParams object
// with the ability to set a context for a request.
func NewListParamsWithContext(ctx context.Context) *ListParams {
	return &ListParams{
		Context: ctx,
	}
}

// NewListParamsWithHTTPClient creates a new ListParams object
// with the ability to set a custom HTTPClient for a request.
func NewListParamsWithHTTPClient(client *http.Client) *ListParams {
	return &ListParams{
		HTTPClient: client,
	}
}

/*
ListParams contains all the parameters to send to the API endpoint

	for the list operation.

	Typically these are written to a http.Request.
*/
type ListParams struct {

	/* ApplicationID.

	   Application id to filter on.

	   Format: int64
	*/
	ApplicationID *string

	/* Limit.

	   Max number of items to return.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset in the result-set (for pagination).

	   Format: int64
	*/
	Offset *string

	/* OrganizationID.

	   Organization id to filter on.

	   Format: int64
	*/
	OrganizationID *string

	/* ProfileID.

	   profile id to filter on.
	*/
	ProfileID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListParams) WithDefaults() *ListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list params
func (o *ListParams) WithTimeout(timeout time.Duration) *ListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list params
func (o *ListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list params
func (o *ListParams) WithContext(ctx context.Context) *ListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list params
func (o *ListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list params
func (o *ListParams) WithHTTPClient(client *http.Client) *ListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list params
func (o *ListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the list params
func (o *ListParams) WithApplicationID(applicationID *string) *ListParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the list params
func (o *ListParams) SetApplicationID(applicationID *string) {
	o.ApplicationID = applicationID
}

// WithLimit adds the limit to the list params
func (o *ListParams) WithLimit(limit *string) *ListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list params
func (o *ListParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the list params
func (o *ListParams) WithOffset(offset *string) *ListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list params
func (o *ListParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the list params
func (o *ListParams) WithOrganizationID(organizationID *string) *ListParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the list params
func (o *ListParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WithProfileID adds the profileID to the list params
func (o *ListParams) WithProfileID(profileID *string) *ListParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the list params
func (o *ListParams) SetProfileID(profileID *string) {
	o.ProfileID = profileID
}

// WriteToRequest writes these params to a swagger request
func (o *ListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ApplicationID != nil {

		// query param applicationID
		var qrApplicationID string

		if o.ApplicationID != nil {
			qrApplicationID = *o.ApplicationID
		}
		qApplicationID := qrApplicationID
		if qApplicationID != "" {

			if err := r.SetQueryParam("applicationID", qApplicationID); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationID
		var qrOrganizationID string

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationID", qOrganizationID); err != nil {
				return err
			}
		}
	}

	if o.ProfileID != nil {

		// query param profileID
		var qrProfileID string

		if o.ProfileID != nil {
			qrProfileID = *o.ProfileID
		}
		qProfileID := qrProfileID
		if qProfileID != "" {

			if err := r.SetQueryParam("profileID", qProfileID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
