// Code generated by go-swagger; DO NOT EDIT.

package multicast_group_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// AddDeviceReader is a Reader for the AddDevice structure.
type AddDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/multicast-groups/{multicastGroupID}/device] AddDevice", response, response.Code())
	}
}

// NewAddDeviceOK creates a AddDeviceOK with default headers values
func NewAddDeviceOK() *AddDeviceOK {
	return &AddDeviceOK{}
}

/*
AddDeviceOK describes a response with status code 200, with default header values.

AddDeviceOK add device o k
*/
type AddDeviceOK struct {
	Payload models.APIEmptyResponse1
}

// IsSuccess returns true when this add device o k response has a 2xx status code
func (o *AddDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add device o k response has a 3xx status code
func (o *AddDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add device o k response has a 4xx status code
func (o *AddDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add device o k response has a 5xx status code
func (o *AddDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add device o k response a status code equal to that given
func (o *AddDeviceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add device o k response
func (o *AddDeviceOK) Code() int {
	return 200
}

func (o *AddDeviceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/multicast-groups/{multicastGroupID}/device][%d] addDeviceOK %s", 200, payload)
}

func (o *AddDeviceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/multicast-groups/{multicastGroupID}/device][%d] addDeviceOK %s", 200, payload)
}

func (o *AddDeviceOK) GetPayload() models.APIEmptyResponse1 {
	return o.Payload
}

func (o *AddDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
