// Code generated by go-swagger; DO NOT EDIT.

package multicast_group_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewAddDeviceParams creates a new AddDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddDeviceParams() *AddDeviceParams {
	return &AddDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddDeviceParamsWithTimeout creates a new AddDeviceParams object
// with the ability to set a timeout on a request.
func NewAddDeviceParamsWithTimeout(timeout time.Duration) *AddDeviceParams {
	return &AddDeviceParams{
		timeout: timeout,
	}
}

// NewAddDeviceParamsWithContext creates a new AddDeviceParams object
// with the ability to set a context for a request.
func NewAddDeviceParamsWithContext(ctx context.Context) *AddDeviceParams {
	return &AddDeviceParams{
		Context: ctx,
	}
}

// NewAddDeviceParamsWithHTTPClient creates a new AddDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddDeviceParamsWithHTTPClient(client *http.Client) *AddDeviceParams {
	return &AddDeviceParams{
		HTTPClient: client,
	}
}

/*
AddDeviceParams contains all the parameters to send to the API endpoint

	for the add device operation.

	Typically these are written to a http.Request.
*/
type AddDeviceParams struct {

	// Body.
	Body *models.APIAddDeviceToMulticastGroupRequest

	/* MulticastGroupID.

	   Multicast-group ID (string formatted UUID).
	*/
	MulticastGroupID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddDeviceParams) WithDefaults() *AddDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add device params
func (o *AddDeviceParams) WithTimeout(timeout time.Duration) *AddDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add device params
func (o *AddDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add device params
func (o *AddDeviceParams) WithContext(ctx context.Context) *AddDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add device params
func (o *AddDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add device params
func (o *AddDeviceParams) WithHTTPClient(client *http.Client) *AddDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add device params
func (o *AddDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add device params
func (o *AddDeviceParams) WithBody(body *models.APIAddDeviceToMulticastGroupRequest) *AddDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add device params
func (o *AddDeviceParams) SetBody(body *models.APIAddDeviceToMulticastGroupRequest) {
	o.Body = body
}

// WithMulticastGroupID adds the multicastGroupID to the add device params
func (o *AddDeviceParams) WithMulticastGroupID(multicastGroupID string) *AddDeviceParams {
	o.SetMulticastGroupID(multicastGroupID)
	return o
}

// SetMulticastGroupID adds the multicastGroupId to the add device params
func (o *AddDeviceParams) SetMulticastGroupID(multicastGroupID string) {
	o.MulticastGroupID = multicastGroupID
}

// WriteToRequest writes these params to a swagger request
func (o *AddDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param multicastGroupID
	if err := r.SetPathParam("multicastGroupID", o.MulticastGroupID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
