// Code generated by go-swagger; DO NOT EDIT.

package multicast_group_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParams creates a new DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParams() *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	return &DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithTimeout creates a new DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithTimeout(timeout time.Duration) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	return &DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithContext creates a new DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithContext(ctx context.Context) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	return &DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithHTTPClient creates a new DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIMulticastGroupsQueueByMulticastGroupIDParamsWithHTTPClient(client *http.Client) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	return &DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams contains all the parameters to send to the API endpoint

	for the delete api multicast groups queue by multicast group ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams struct {

	/* MulticastGroupID.

	   Multicast-group ID (string formatted UUID).
	*/
	MulticastGroupID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete api multicast groups queue by multicast group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WithDefaults() *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete api multicast groups queue by multicast group ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WithTimeout(timeout time.Duration) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WithContext(ctx context.Context) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WithHTTPClient(client *http.Client) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMulticastGroupID adds the multicastGroupID to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WithMulticastGroupID(multicastGroupID string) *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams {
	o.SetMulticastGroupID(multicastGroupID)
	return o
}

// SetMulticastGroupID adds the multicastGroupId to the delete api multicast groups queue by multicast group ID params
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) SetMulticastGroupID(multicastGroupID string) {
	o.MulticastGroupID = multicastGroupID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIMulticastGroupsQueueByMulticastGroupIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param multicastGroupID
	if err := r.SetPathParam("multicastGroupID", o.MulticastGroupID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
