// Code generated by go-swagger; DO NOT EDIT.

package multicast_group_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PutAPIMulticastGroupsMulticastGroupIDReader is a Reader for the PutAPIMulticastGroupsMulticastGroupID structure.
type PutAPIMulticastGroupsMulticastGroupIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIMulticastGroupsMulticastGroupIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIMulticastGroupsMulticastGroupIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/multicast-groups/{multicastGroup.id}] PutAPIMulticastGroupsMulticastGroupID", response, response.Code())
	}
}

// NewPutAPIMulticastGroupsMulticastGroupIDOK creates a PutAPIMulticastGroupsMulticastGroupIDOK with default headers values
func NewPutAPIMulticastGroupsMulticastGroupIDOK() *PutAPIMulticastGroupsMulticastGroupIDOK {
	return &PutAPIMulticastGroupsMulticastGroupIDOK{}
}

/*
PutAPIMulticastGroupsMulticastGroupIDOK describes a response with status code 200, with default header values.

PutAPIMulticastGroupsMulticastGroupIDOK put Api multicast groups multicast group Id o k
*/
type PutAPIMulticastGroupsMulticastGroupIDOK struct {
	Payload models.APIEmptyResponse1
}

// IsSuccess returns true when this put Api multicast groups multicast group Id o k response has a 2xx status code
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api multicast groups multicast group Id o k response has a 3xx status code
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api multicast groups multicast group Id o k response has a 4xx status code
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api multicast groups multicast group Id o k response has a 5xx status code
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api multicast groups multicast group Id o k response a status code equal to that given
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api multicast groups multicast group Id o k response
func (o *PutAPIMulticastGroupsMulticastGroupIDOK) Code() int {
	return 200
}

func (o *PutAPIMulticastGroupsMulticastGroupIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/multicast-groups/{multicastGroup.id}][%d] putApiMulticastGroupsMulticastGroupIdOK %s", 200, payload)
}

func (o *PutAPIMulticastGroupsMulticastGroupIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/multicast-groups/{multicastGroup.id}][%d] putApiMulticastGroupsMulticastGroupIdOK %s", 200, payload)
}

func (o *PutAPIMulticastGroupsMulticastGroupIDOK) GetPayload() models.APIEmptyResponse1 {
	return o.Payload
}

func (o *PutAPIMulticastGroupsMulticastGroupIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
