// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// ActivateReader is a Reader for the Activate structure.
type ActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/devices/{devEUI}/activate] Activate", response, response.Code())
	}
}

// NewActivateOK creates a ActivateOK with default headers values
func NewActivateOK() *ActivateOK {
	return &ActivateOK{}
}

/*
ActivateOK describes a response with status code 200, with default header values.

ActivateOK activate o k
*/
type ActivateOK struct {
	Payload models.APIActivateDeviceResponse
}

// IsSuccess returns true when this activate o k response has a 2xx status code
func (o *ActivateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activate o k response has a 3xx status code
func (o *ActivateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activate o k response has a 4xx status code
func (o *ActivateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activate o k response has a 5xx status code
func (o *ActivateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activate o k response a status code equal to that given
func (o *ActivateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the activate o k response
func (o *ActivateOK) Code() int {
	return 200
}

func (o *ActivateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices/{devEUI}/activate][%d] activateOK %s", 200, payload)
}

func (o *ActivateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices/{devEUI}/activate][%d] activateOK %s", 200, payload)
}

func (o *ActivateOK) GetPayload() models.APIActivateDeviceResponse {
	return o.Payload
}

func (o *ActivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
