// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIDevicesKeysByDevEUIParams creates a new DeleteAPIDevicesKeysByDevEUIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIDevicesKeysByDevEUIParams() *DeleteAPIDevicesKeysByDevEUIParams {
	return &DeleteAPIDevicesKeysByDevEUIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIDevicesKeysByDevEUIParamsWithTimeout creates a new DeleteAPIDevicesKeysByDevEUIParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIDevicesKeysByDevEUIParamsWithTimeout(timeout time.Duration) *DeleteAPIDevicesKeysByDevEUIParams {
	return &DeleteAPIDevicesKeysByDevEUIParams{
		timeout: timeout,
	}
}

// NewDeleteAPIDevicesKeysByDevEUIParamsWithContext creates a new DeleteAPIDevicesKeysByDevEUIParams object
// with the ability to set a context for a request.
func NewDeleteAPIDevicesKeysByDevEUIParamsWithContext(ctx context.Context) *DeleteAPIDevicesKeysByDevEUIParams {
	return &DeleteAPIDevicesKeysByDevEUIParams{
		Context: ctx,
	}
}

// NewDeleteAPIDevicesKeysByDevEUIParamsWithHTTPClient creates a new DeleteAPIDevicesKeysByDevEUIParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIDevicesKeysByDevEUIParamsWithHTTPClient(client *http.Client) *DeleteAPIDevicesKeysByDevEUIParams {
	return &DeleteAPIDevicesKeysByDevEUIParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIDevicesKeysByDevEUIParams contains all the parameters to send to the API endpoint

	for the delete api devices keys by dev e UI operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIDevicesKeysByDevEUIParams struct {

	/* DevEUI.

	   Hex encoded DevEUI of the device.
	*/
	DevEUI string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete api devices keys by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIDevicesKeysByDevEUIParams) WithDefaults() *DeleteAPIDevicesKeysByDevEUIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete api devices keys by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIDevicesKeysByDevEUIParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) WithTimeout(timeout time.Duration) *DeleteAPIDevicesKeysByDevEUIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) WithContext(ctx context.Context) *DeleteAPIDevicesKeysByDevEUIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) WithHTTPClient(client *http.Client) *DeleteAPIDevicesKeysByDevEUIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevEUI adds the devEUI to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) WithDevEUI(devEUI string) *DeleteAPIDevicesKeysByDevEUIParams {
	o.SetDevEUI(devEUI)
	return o
}

// SetDevEUI adds the devEUi to the delete api devices keys by dev e UI params
func (o *DeleteAPIDevicesKeysByDevEUIParams) SetDevEUI(devEUI string) {
	o.DevEUI = devEUI
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIDevicesKeysByDevEUIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devEUI
	if err := r.SetPathParam("devEUI", o.DevEUI); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
