// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIApplicationsDevicesByApplicationIDReader is a Reader for the GetAPIApplicationsDevicesByApplicationID structure.
type GetAPIApplicationsDevicesByApplicationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationsDevicesByApplicationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationsDevicesByApplicationIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/applications/{applicationID}/devices] get_api_applications_devices_by_applicationID", response, response.Code())
	}
}

// NewGetAPIApplicationsDevicesByApplicationIDOK creates a GetAPIApplicationsDevicesByApplicationIDOK with default headers values
func NewGetAPIApplicationsDevicesByApplicationIDOK() *GetAPIApplicationsDevicesByApplicationIDOK {
	return &GetAPIApplicationsDevicesByApplicationIDOK{}
}

/*
GetAPIApplicationsDevicesByApplicationIDOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIApplicationsDevicesByApplicationIDOK struct {
	Payload *models.APIListDeviceResponse
}

// IsSuccess returns true when this get Api applications devices by application Id o k response has a 2xx status code
func (o *GetAPIApplicationsDevicesByApplicationIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api applications devices by application Id o k response has a 3xx status code
func (o *GetAPIApplicationsDevicesByApplicationIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api applications devices by application Id o k response has a 4xx status code
func (o *GetAPIApplicationsDevicesByApplicationIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api applications devices by application Id o k response has a 5xx status code
func (o *GetAPIApplicationsDevicesByApplicationIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api applications devices by application Id o k response a status code equal to that given
func (o *GetAPIApplicationsDevicesByApplicationIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api applications devices by application Id o k response
func (o *GetAPIApplicationsDevicesByApplicationIDOK) Code() int {
	return 200
}

func (o *GetAPIApplicationsDevicesByApplicationIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{applicationID}/devices][%d] getApiApplicationsDevicesByApplicationIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsDevicesByApplicationIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{applicationID}/devices][%d] getApiApplicationsDevicesByApplicationIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsDevicesByApplicationIDOK) GetPayload() *models.APIListDeviceResponse {
	return o.Payload
}

func (o *GetAPIApplicationsDevicesByApplicationIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIListDeviceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
