// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIDevicesEventsByDevEUIParams creates a new GetAPIDevicesEventsByDevEUIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIDevicesEventsByDevEUIParams() *GetAPIDevicesEventsByDevEUIParams {
	return &GetAPIDevicesEventsByDevEUIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIDevicesEventsByDevEUIParamsWithTimeout creates a new GetAPIDevicesEventsByDevEUIParams object
// with the ability to set a timeout on a request.
func NewGetAPIDevicesEventsByDevEUIParamsWithTimeout(timeout time.Duration) *GetAPIDevicesEventsByDevEUIParams {
	return &GetAPIDevicesEventsByDevEUIParams{
		timeout: timeout,
	}
}

// NewGetAPIDevicesEventsByDevEUIParamsWithContext creates a new GetAPIDevicesEventsByDevEUIParams object
// with the ability to set a context for a request.
func NewGetAPIDevicesEventsByDevEUIParamsWithContext(ctx context.Context) *GetAPIDevicesEventsByDevEUIParams {
	return &GetAPIDevicesEventsByDevEUIParams{
		Context: ctx,
	}
}

// NewGetAPIDevicesEventsByDevEUIParamsWithHTTPClient creates a new GetAPIDevicesEventsByDevEUIParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIDevicesEventsByDevEUIParamsWithHTTPClient(client *http.Client) *GetAPIDevicesEventsByDevEUIParams {
	return &GetAPIDevicesEventsByDevEUIParams{
		HTTPClient: client,
	}
}

/*
GetAPIDevicesEventsByDevEUIParams contains all the parameters to send to the API endpoint

	for the get api devices events by dev e UI operation.

	Typically these are written to a http.Request.
*/
type GetAPIDevicesEventsByDevEUIParams struct {

	/* DevEUI.

	   Hex encoded DevEUI.
	*/
	DevEUI string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get api devices events by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIDevicesEventsByDevEUIParams) WithDefaults() *GetAPIDevicesEventsByDevEUIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get api devices events by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIDevicesEventsByDevEUIParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) WithTimeout(timeout time.Duration) *GetAPIDevicesEventsByDevEUIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) WithContext(ctx context.Context) *GetAPIDevicesEventsByDevEUIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) WithHTTPClient(client *http.Client) *GetAPIDevicesEventsByDevEUIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevEUI adds the devEUI to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) WithDevEUI(devEUI string) *GetAPIDevicesEventsByDevEUIParams {
	o.SetDevEUI(devEUI)
	return o
}

// SetDevEUI adds the devEUi to the get api devices events by dev e UI params
func (o *GetAPIDevicesEventsByDevEUIParams) SetDevEUI(devEUI string) {
	o.DevEUI = devEUI
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIDevicesEventsByDevEUIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devEUI
	if err := r.SetPathParam("devEUI", o.DevEUI); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
