// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetKeysReader is a Reader for the GetKeys structure.
type GetKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/devices/{devEUI}/keys] GetKeys", response, response.Code())
	}
}

// NewGetKeysOK creates a GetKeysOK with default headers values
func NewGetKeysOK() *GetKeysOK {
	return &GetKeysOK{}
}

/*
GetKeysOK describes a response with status code 200, with default header values.

GetKeysOK get keys o k
*/
type GetKeysOK struct {
	Payload *models.APIGetDeviceKeysResponse
}

// IsSuccess returns true when this get keys o k response has a 2xx status code
func (o *GetKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get keys o k response has a 3xx status code
func (o *GetKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get keys o k response has a 4xx status code
func (o *GetKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get keys o k response has a 5xx status code
func (o *GetKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get keys o k response a status code equal to that given
func (o *GetKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get keys o k response
func (o *GetKeysOK) Code() int {
	return 200
}

func (o *GetKeysOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/devices/{devEUI}/keys][%d] getKeysOK %s", 200, payload)
}

func (o *GetKeysOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/devices/{devEUI}/keys][%d] getKeysOK %s", 200, payload)
}

func (o *GetKeysOK) GetPayload() *models.APIGetDeviceKeysResponse {
	return o.Payload
}

func (o *GetKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetDeviceKeysResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
