// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListByApplicationIDParams creates a new ListByApplicationIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListByApplicationIDParams() *ListByApplicationIDParams {
	return &ListByApplicationIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListByApplicationIDParamsWithTimeout creates a new ListByApplicationIDParams object
// with the ability to set a timeout on a request.
func NewListByApplicationIDParamsWithTimeout(timeout time.Duration) *ListByApplicationIDParams {
	return &ListByApplicationIDParams{
		timeout: timeout,
	}
}

// NewListByApplicationIDParamsWithContext creates a new ListByApplicationIDParams object
// with the ability to set a context for a request.
func NewListByApplicationIDParamsWithContext(ctx context.Context) *ListByApplicationIDParams {
	return &ListByApplicationIDParams{
		Context: ctx,
	}
}

// NewListByApplicationIDParamsWithHTTPClient creates a new ListByApplicationIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewListByApplicationIDParamsWithHTTPClient(client *http.Client) *ListByApplicationIDParams {
	return &ListByApplicationIDParams{
		HTTPClient: client,
	}
}

/*
ListByApplicationIDParams contains all the parameters to send to the API endpoint

	for the list by application ID operation.

	Typically these are written to a http.Request.
*/
type ListByApplicationIDParams struct {

	/* ApplicationID.

	   ID of the application for which to list the devices.

	   Format: int64
	*/
	ApplicationID string

	/* Limit.

	   Max number of devices to return in the result-set.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset of the result-set (for pagination).

	   Format: int64
	*/
	Offset *string

	/* Search.

	   Search against name or DevEUI.
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list by application ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListByApplicationIDParams) WithDefaults() *ListByApplicationIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list by application ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListByApplicationIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list by application ID params
func (o *ListByApplicationIDParams) WithTimeout(timeout time.Duration) *ListByApplicationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list by application ID params
func (o *ListByApplicationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list by application ID params
func (o *ListByApplicationIDParams) WithContext(ctx context.Context) *ListByApplicationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list by application ID params
func (o *ListByApplicationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list by application ID params
func (o *ListByApplicationIDParams) WithHTTPClient(client *http.Client) *ListByApplicationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list by application ID params
func (o *ListByApplicationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the list by application ID params
func (o *ListByApplicationIDParams) WithApplicationID(applicationID string) *ListByApplicationIDParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the list by application ID params
func (o *ListByApplicationIDParams) SetApplicationID(applicationID string) {
	o.ApplicationID = applicationID
}

// WithLimit adds the limit to the list by application ID params
func (o *ListByApplicationIDParams) WithLimit(limit *string) *ListByApplicationIDParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list by application ID params
func (o *ListByApplicationIDParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the list by application ID params
func (o *ListByApplicationIDParams) WithOffset(offset *string) *ListByApplicationIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list by application ID params
func (o *ListByApplicationIDParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithSearch adds the search to the list by application ID params
func (o *ListByApplicationIDParams) WithSearch(search *string) *ListByApplicationIDParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the list by application ID params
func (o *ListByApplicationIDParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *ListByApplicationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param applicationID
	if err := r.SetPathParam("applicationID", o.ApplicationID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
