// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIDevicesActivateByDevEUIReader is a Reader for the PostAPIDevicesActivateByDevEUI structure.
type PostAPIDevicesActivateByDevEUIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIDevicesActivateByDevEUIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIDevicesActivateByDevEUIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/devices/{devEUI}/activate] post_api_devices_activate_by_devEUI", response, response.Code())
	}
}

// NewPostAPIDevicesActivateByDevEUIOK creates a PostAPIDevicesActivateByDevEUIOK with default headers values
func NewPostAPIDevicesActivateByDevEUIOK() *PostAPIDevicesActivateByDevEUIOK {
	return &PostAPIDevicesActivateByDevEUIOK{}
}

/*
PostAPIDevicesActivateByDevEUIOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIDevicesActivateByDevEUIOK struct {
	Payload models.APIActivateDeviceResponse
}

// IsSuccess returns true when this post Api devices activate by dev e Ui o k response has a 2xx status code
func (o *PostAPIDevicesActivateByDevEUIOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api devices activate by dev e Ui o k response has a 3xx status code
func (o *PostAPIDevicesActivateByDevEUIOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api devices activate by dev e Ui o k response has a 4xx status code
func (o *PostAPIDevicesActivateByDevEUIOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api devices activate by dev e Ui o k response has a 5xx status code
func (o *PostAPIDevicesActivateByDevEUIOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api devices activate by dev e Ui o k response a status code equal to that given
func (o *PostAPIDevicesActivateByDevEUIOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api devices activate by dev e Ui o k response
func (o *PostAPIDevicesActivateByDevEUIOK) Code() int {
	return 200
}

func (o *PostAPIDevicesActivateByDevEUIOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices/{devEUI}/activate][%d] postApiDevicesActivateByDevEUiOK %s", 200, payload)
}

func (o *PostAPIDevicesActivateByDevEUIOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices/{devEUI}/activate][%d] postApiDevicesActivateByDevEUiOK %s", 200, payload)
}

func (o *PostAPIDevicesActivateByDevEUIOK) GetPayload() models.APIActivateDeviceResponse {
	return o.Payload
}

func (o *PostAPIDevicesActivateByDevEUIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
