// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIDevicesReader is a Reader for the PostAPIDevices structure.
type PostAPIDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/devices] post_api_devices", response, response.Code())
	}
}

// NewPostAPIDevicesOK creates a PostAPIDevicesOK with default headers values
func NewPostAPIDevicesOK() *PostAPIDevicesOK {
	return &PostAPIDevicesOK{}
}

/*
PostAPIDevicesOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIDevicesOK struct {
	Payload models.APICreateDeviceResponse
}

// IsSuccess returns true when this post Api devices o k response has a 2xx status code
func (o *PostAPIDevicesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api devices o k response has a 3xx status code
func (o *PostAPIDevicesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api devices o k response has a 4xx status code
func (o *PostAPIDevicesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api devices o k response has a 5xx status code
func (o *PostAPIDevicesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api devices o k response a status code equal to that given
func (o *PostAPIDevicesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api devices o k response
func (o *PostAPIDevicesOK) Code() int {
	return 200
}

func (o *PostAPIDevicesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices][%d] postApiDevicesOK %s", 200, payload)
}

func (o *PostAPIDevicesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/devices][%d] postApiDevicesOK %s", 200, payload)
}

func (o *PostAPIDevicesOK) GetPayload() models.APICreateDeviceResponse {
	return o.Payload
}

func (o *PostAPIDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
