// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PutAPIDevicesKeysByDevEUIReader is a Reader for the PutAPIDevicesKeysByDevEUI structure.
type PutAPIDevicesKeysByDevEUIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIDevicesKeysByDevEUIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIDevicesKeysByDevEUIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/devices/{devEUI}/keys] put_api_devices_keys_by_devEUI", response, response.Code())
	}
}

// NewPutAPIDevicesKeysByDevEUIOK creates a PutAPIDevicesKeysByDevEUIOK with default headers values
func NewPutAPIDevicesKeysByDevEUIOK() *PutAPIDevicesKeysByDevEUIOK {
	return &PutAPIDevicesKeysByDevEUIOK{}
}

/*
PutAPIDevicesKeysByDevEUIOK describes a response with status code 200, with default header values.

(empty)
*/
type PutAPIDevicesKeysByDevEUIOK struct {
	Payload models.APIUpdateDeviceKeysResponse
}

// IsSuccess returns true when this put Api devices keys by dev e Ui o k response has a 2xx status code
func (o *PutAPIDevicesKeysByDevEUIOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api devices keys by dev e Ui o k response has a 3xx status code
func (o *PutAPIDevicesKeysByDevEUIOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api devices keys by dev e Ui o k response has a 4xx status code
func (o *PutAPIDevicesKeysByDevEUIOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api devices keys by dev e Ui o k response has a 5xx status code
func (o *PutAPIDevicesKeysByDevEUIOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api devices keys by dev e Ui o k response a status code equal to that given
func (o *PutAPIDevicesKeysByDevEUIOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api devices keys by dev e Ui o k response
func (o *PutAPIDevicesKeysByDevEUIOK) Code() int {
	return 200
}

func (o *PutAPIDevicesKeysByDevEUIOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/devices/{devEUI}/keys][%d] putApiDevicesKeysByDevEUiOK %s", 200, payload)
}

func (o *PutAPIDevicesKeysByDevEUIOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/devices/{devEUI}/keys][%d] putApiDevicesKeysByDevEUiOK %s", 200, payload)
}

func (o *PutAPIDevicesKeysByDevEUIOK) GetPayload() models.APIUpdateDeviceKeysResponse {
	return o.Payload
}

func (o *PutAPIDevicesKeysByDevEUIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
