// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIDevicesByDevEUIParams creates a new PutAPIDevicesByDevEUIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIDevicesByDevEUIParams() *PutAPIDevicesByDevEUIParams {
	return &PutAPIDevicesByDevEUIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIDevicesByDevEUIParamsWithTimeout creates a new PutAPIDevicesByDevEUIParams object
// with the ability to set a timeout on a request.
func NewPutAPIDevicesByDevEUIParamsWithTimeout(timeout time.Duration) *PutAPIDevicesByDevEUIParams {
	return &PutAPIDevicesByDevEUIParams{
		timeout: timeout,
	}
}

// NewPutAPIDevicesByDevEUIParamsWithContext creates a new PutAPIDevicesByDevEUIParams object
// with the ability to set a context for a request.
func NewPutAPIDevicesByDevEUIParamsWithContext(ctx context.Context) *PutAPIDevicesByDevEUIParams {
	return &PutAPIDevicesByDevEUIParams{
		Context: ctx,
	}
}

// NewPutAPIDevicesByDevEUIParamsWithHTTPClient creates a new PutAPIDevicesByDevEUIParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIDevicesByDevEUIParamsWithHTTPClient(client *http.Client) *PutAPIDevicesByDevEUIParams {
	return &PutAPIDevicesByDevEUIParams{
		HTTPClient: client,
	}
}

/*
PutAPIDevicesByDevEUIParams contains all the parameters to send to the API endpoint

	for the put api devices by dev e UI operation.

	Typically these are written to a http.Request.
*/
type PutAPIDevicesByDevEUIParams struct {

	// Body.
	Body *models.APIUpdateDeviceRequest

	/* DevEUI.

	   Hex encoded DevEUI.
	*/
	DevEUI string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put api devices by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIDevicesByDevEUIParams) WithDefaults() *PutAPIDevicesByDevEUIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put api devices by dev e UI params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIDevicesByDevEUIParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) WithTimeout(timeout time.Duration) *PutAPIDevicesByDevEUIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) WithContext(ctx context.Context) *PutAPIDevicesByDevEUIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) WithHTTPClient(client *http.Client) *PutAPIDevicesByDevEUIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) WithBody(body *models.APIUpdateDeviceRequest) *PutAPIDevicesByDevEUIParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) SetBody(body *models.APIUpdateDeviceRequest) {
	o.Body = body
}

// WithDevEUI adds the devEUI to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) WithDevEUI(devEUI string) *PutAPIDevicesByDevEUIParams {
	o.SetDevEUI(devEUI)
	return o
}

// SetDevEUI adds the devEUi to the put api devices by dev e UI params
func (o *PutAPIDevicesByDevEUIParams) SetDevEUI(devEUI string) {
	o.DevEUI = devEUI
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIDevicesByDevEUIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param devEUI
	if err := r.SetPathParam("devEUI", o.DevEUI); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
