// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIFuotaDevice api fuota device
//
// swagger:model apiFuotaDevice
type APIFuotaDevice struct {

	// dev eui
	DevEui string `json:"dev_eui,omitempty"`

	// firmware version
	FirmwareVersion string `json:"firmware_version,omitempty"`

	// fragment session status
	FragmentSessionStatus int32 `json:"fragment_session_status,omitempty"`

	// hardware version
	HardwareVersion string `json:"hardware_version,omitempty"`

	// multicast session status
	MulticastSessionStatus int32 `json:"multicast_session_status,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// product model
	ProductModel string `json:"product_model,omitempty"`

	// profile id
	ProfileID string `json:"profile_id,omitempty"`

	// profile name
	ProfileName string `json:"profile_name,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`

	// task id
	TaskID int32 `json:"task_id,omitempty"`
}

// Validate validates this api fuota device
func (m *APIFuotaDevice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api fuota device based on context it is used
func (m *APIFuotaDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIFuotaDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFuotaDevice) UnmarshalBinary(b []byte) error {
	var res APIFuotaDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
