// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIURCreateApplicationResponse api u r create application response
//
// swagger:model apiURCreateApplicationResponse
type APIURCreateApplicationResponse struct {

	// ID of the application that was created.
	ID string `json:"id,omitempty"`
}

// Validate validates this api u r create application response
func (m *APIURCreateApplicationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api u r create application response based on context it is used
func (m *APIURCreateApplicationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIURCreateApplicationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIURCreateApplicationResponse) UnmarshalBinary(b []byte) error {
	var res APIURCreateApplicationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
