// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUrListSimpleDeviceResponse api ur list simple device response
//
// swagger:model apiUrListSimpleDeviceResponse
type APIUrListSimpleDeviceResponse struct {

	// Total number of devices available within the deviceResult-set
	DevTotalCount string `json:"devTotalCount,omitempty"`

	// Devices within this deviceResult-set
	DeviceResult []*APISimpleDeviceItem `json:"deviceResult"`
}

// Validate validates this api ur list simple device response
func (m *APIUrListSimpleDeviceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUrListSimpleDeviceResponse) validateDeviceResult(formats strfmt.Registry) error {
	if swag.IsZero(m.DeviceResult) { // not required
		return nil
	}

	for i := 0; i < len(m.DeviceResult); i++ {
		if swag.IsZero(m.DeviceResult[i]) { // not required
			continue
		}

		if m.DeviceResult[i] != nil {
			if err := m.DeviceResult[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deviceResult" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deviceResult" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this api ur list simple device response based on the context it is used
func (m *APIUrListSimpleDeviceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeviceResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUrListSimpleDeviceResponse) contextValidateDeviceResult(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DeviceResult); i++ {

		if m.DeviceResult[i] != nil {

			if swag.IsZero(m.DeviceResult[i]) { // not required
				return nil
			}

			if err := m.DeviceResult[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deviceResult" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deviceResult" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIUrListSimpleDeviceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUrListSimpleDeviceResponse) UnmarshalBinary(b []byte) error {
	var res APIUrListSimpleDeviceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
