// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIImportPayloadCodecResponse api import payload codec response
//
// swagger:model apiImportPayloadCodecResponse
type APIImportPayloadCodecResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// fail count
	FailCount int64 `json:"failCount,omitempty"`

	// succ count
	SuccCount int64 `json:"succCount,omitempty"`
}

// Validate validates this api import payload codec response
func (m *APIImportPayloadCodecResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api import payload codec response based on context it is used
func (m *APIImportPayloadCodecResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIImportPayloadCodecResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIImportPayloadCodecResponse) UnmarshalBinary(b []byte) error {
	var res APIImportPayloadCodecResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
