// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIGetModbusObjectRequest api get modbus object request
//
// swagger:model apiGetModbusObjectRequest
type APIGetModbusObjectRequest struct {

	// limit
	Limit int32 `json:"limit,omitempty"`

	// offset
	Offset int32 `json:"offset,omitempty"`

	// order
	Order string `json:"order,omitempty"`

	// search
	Search string `json:"search,omitempty"`

	// server id
	ServerID string `json:"server_id,omitempty"`

	// sort
	Sort string `json:"sort,omitempty"`
}

// Validate validates this api get modbus object request
func (m *APIGetModbusObjectRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api get modbus object request based on context it is used
func (m *APIGetModbusObjectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIGetModbusObjectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIGetModbusObjectRequest) UnmarshalBinary(b []byte) error {
	var res APIGetModbusObjectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
