// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMulticastGroup api multicast group
//
// swagger:model apiMulticastGroup
type APIMulticastGroup struct {

	// Data-rate.
	Dr int64 `json:"dr,omitempty"`

	// Frame-counter.
	FCnt int64 `json:"fCnt,omitempty"`

	// Frequency (Hz).
	Frequency int64 `json:"frequency,omitempty"`

	// Multicast type.
	GroupType *APIMulticastGroupType `json:"groupType,omitempty"`

	// ID (string formatted UUID).
	// This will be generated automatically on create.
	ID string `json:"id,omitempty"`

	// Multicast address (HEX encoded DevAddr).
	McAddr string `json:"mcAddr,omitempty"`

	// Multicast application session key (HEX encoded AES128 key).
	McAppSKey string `json:"mcAppSKey,omitempty"`

	// Multicast network session key (HEX encoded AES128 key).
	McNwkSKey string `json:"mcNwkSKey,omitempty"`

	// Multicast-group name.
	Name string `json:"name,omitempty"`

	// Ping-slot period.
	// Mandatory for Class-B multicast groups.
	PingSlotPeriod int64 `json:"pingSlotPeriod,omitempty"`
}

// Validate validates this api multicast group
func (m *APIMulticastGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIMulticastGroup) validateGroupType(formats strfmt.Registry) error {
	if swag.IsZero(m.GroupType) { // not required
		return nil
	}

	if m.GroupType != nil {
		if err := m.GroupType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("groupType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("groupType")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this api multicast group based on the context it is used
func (m *APIMulticastGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGroupType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIMulticastGroup) contextValidateGroupType(ctx context.Context, formats strfmt.Registry) error {

	if m.GroupType != nil {

		if swag.IsZero(m.GroupType) { // not required
			return nil
		}

		if err := m.GroupType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("groupType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("groupType")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIMulticastGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMulticastGroup) UnmarshalBinary(b []byte) error {
	var res APIMulticastGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
