// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIServiceProfile api service profile
//
// swagger:model apiServiceProfile
type APIServiceProfile struct {

	// add g w metadata
	AddGWMetadata bool `json:"addGWMetadata,omitempty"`

	// channel mask
	// Format: byte
	ChannelMask strfmt.Base64 `json:"channelMask,omitempty"`

	// dev status req freq
	DevStatusReqFreq int64 `json:"devStatusReqFreq,omitempty"`

	// dl bucket size
	DlBucketSize int64 `json:"dlBucketSize,omitempty"`

	// dl rate
	DlRate int64 `json:"dlRate,omitempty"`

	// dl rate policy
	DlRatePolicy *APIRatePolicy `json:"dlRatePolicy,omitempty"`

	// dr max
	DrMax int64 `json:"drMax,omitempty"`

	// dr min
	DrMin int64 `json:"drMin,omitempty"`

	// hr allowed
	HrAllowed bool `json:"hrAllowed,omitempty"`

	// min g w diversity
	MinGWDiversity int64 `json:"minGWDiversity,omitempty"`

	// nwk geo loc
	NwkGeoLoc bool `json:"nwkGeoLoc,omitempty"`

	// pr allowed
	PrAllowed bool `json:"prAllowed,omitempty"`

	// ra allowed
	RaAllowed bool `json:"raAllowed,omitempty"`

	// report dev status battery
	ReportDevStatusBattery bool `json:"reportDevStatusBattery,omitempty"`

	// report dev status margin
	ReportDevStatusMargin bool `json:"reportDevStatusMargin,omitempty"`

	// service profile ID
	ServiceProfileID string `json:"serviceProfileID,omitempty"`

	// target p e r
	TargetPER int64 `json:"targetPER,omitempty"`

	// ul bucket size
	UlBucketSize int64 `json:"ulBucketSize,omitempty"`

	// ul rate
	UlRate int64 `json:"ulRate,omitempty"`

	// ul rate policy
	UlRatePolicy *APIRatePolicy `json:"ulRatePolicy,omitempty"`
}

// Validate validates this api service profile
func (m *APIServiceProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDlRatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUlRatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceProfile) validateDlRatePolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.DlRatePolicy) { // not required
		return nil
	}

	if m.DlRatePolicy != nil {
		if err := m.DlRatePolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dlRatePolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dlRatePolicy")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceProfile) validateUlRatePolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.UlRatePolicy) { // not required
		return nil
	}

	if m.UlRatePolicy != nil {
		if err := m.UlRatePolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ulRatePolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ulRatePolicy")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this api service profile based on the context it is used
func (m *APIServiceProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDlRatePolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUlRatePolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceProfile) contextValidateDlRatePolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.DlRatePolicy != nil {

		if swag.IsZero(m.DlRatePolicy) { // not required
			return nil
		}

		if err := m.DlRatePolicy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dlRatePolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dlRatePolicy")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceProfile) contextValidateUlRatePolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.UlRatePolicy != nil {

		if swag.IsZero(m.UlRatePolicy) { // not required
			return nil
		}

		if err := m.UlRatePolicy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ulRatePolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ulRatePolicy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIServiceProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIServiceProfile) UnmarshalBinary(b []byte) error {
	var res APIServiceProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
