// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// APIUpdateFuotaTaskResponse api update fuota task response
//
// swagger:model apiUpdateFuotaTaskResponse
type APIUpdateFuotaTaskResponse interface{}
