// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUrbridge api urbridge
//
// swagger:model apiUrbridge
type APIUrbridge struct {

	// ca cert
	CaCert string `json:"caCert,omitempty"`

	// ca cert path
	CaCertPath string `json:"caCertPath,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// region Id
	RegionID string `json:"regionId,omitempty"`

	// serv addr
	ServAddr string `json:"servAddr,omitempty"`

	// serv enabled
	ServEnabled bool `json:"servEnabled,omitempty"`

	// serv mqtt port
	ServMqttPort int64 `json:"servMqttPort,omitempty"`

	// serv port down
	ServPortDown int64 `json:"servPortDown,omitempty"`

	// serv port up
	ServPortUp int64 `json:"servPortUp,omitempty"`

	// serv type
	ServType string `json:"servType,omitempty"`

	// sync freq plan
	SyncFreqPlan bool `json:"syncFreqPlan,omitempty"`

	// tls cert
	TLSCert string `json:"tlsCert,omitempty"`

	// tls cert path
	TLSCertPath string `json:"tlsCertPath,omitempty"`

	// tls key
	TLSKey string `json:"tlsKey,omitempty"`

	// tls key path
	TLSKeyPath string `json:"tlsKeyPath,omitempty"`

	// tls mode
	TLSMode int64 `json:"tlsMode,omitempty"`

	// use cred
	UseCred bool `json:"useCred,omitempty"`

	// use Tls
	UseTLS bool `json:"useTls,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this api urbridge
func (m *APIUrbridge) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api urbridge based on context it is used
func (m *APIUrbridge) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUrbridge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUrbridge) UnmarshalBinary(b []byte) error {
	var res APIUrbridge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
