// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APITestPayloadCodecRequest api test payload codec request
//
// swagger:model apiTestPayloadCodecRequest
type APITestPayloadCodecRequest struct {

	// data
	Data string `json:"data,omitempty"`

	// f port
	FPort int64 `json:"fPort,omitempty"`

	// script
	Script string `json:"script,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this api test payload codec request
func (m *APITestPayloadCodecRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api test payload codec request based on context it is used
func (m *APITestPayloadCodecRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APITestPayloadCodecRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APITestPayloadCodecRequest) UnmarshalBinary(b []byte) error {
	var res APITestPayloadCodecRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
