// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUnitPCO PCO 单位信息
//
// swagger:model apiUnitPCO
type APIUnitPCO struct {

	// 单位名称
	Unit string `json:"unit,omitempty"`

	// 单位类型 ID
	UnitTypeID int32 `json:"unitTypeId,omitempty"`
}

// Validate validates this api unit p c o
func (m *APIUnitPCO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api unit p c o based on context it is used
func (m *APIUnitPCO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUnitPCO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUnitPCO) UnmarshalBinary(b []byte) error {
	var res APIUnitPCO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
