// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIGetDeviceActivationResponse api get device activation response
//
// swagger:model apiGetDeviceActivationResponse
type APIGetDeviceActivationResponse struct {

	// Hex encoded AppSKey.
	AppSKey string `json:"appSKey,omitempty"`

	// Hex encoded DevAddr.
	DevAddr string `json:"devAddr,omitempty"`

	// Downlink frame-counter.
	FCntDown int64 `json:"fCntDown,omitempty"`

	// Uplink frame-counter.
	FCntUp int64 `json:"fCntUp,omitempty"`

	// Hex encoded NwkSKey.
	NwkSKey string `json:"nwkSKey,omitempty"`

	// Skip frame-counter checks (this is insecure, but could be helpful for debugging).
	SkipFCntCheck bool `json:"skipFCntCheck,omitempty"`
}

// Validate validates this api get device activation response
func (m *APIGetDeviceActivationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api get device activation response based on context it is used
func (m *APIGetDeviceActivationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIGetDeviceActivationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIGetDeviceActivationResponse) UnmarshalBinary(b []byte) error {
	var res APIGetDeviceActivationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
