// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUrStreamDeviceDataResponse api ur stream device data response
//
// swagger:model apiUrStreamDeviceDataResponse
type APIUrStreamDeviceDataResponse struct {

	// The data payload in JSON encoding.
	PayloadJSON string `json:"payloadJSON,omitempty"`

	// The data type.
	Type string `json:"type,omitempty"`
}

// Validate validates this api ur stream device data response
func (m *APIUrStreamDeviceDataResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api ur stream device data response based on context it is used
func (m *APIUrStreamDeviceDataResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUrStreamDeviceDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUrStreamDeviceDataResponse) UnmarshalBinary(b []byte) error {
	var res APIUrStreamDeviceDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
