// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIHTTPIntegrationHeader api HTTP integration header
//
// swagger:model apiHTTPIntegrationHeader
type APIHTTPIntegrationHeader struct {

	// Key
	Key string `json:"key,omitempty"`

	// Value
	Value string `json:"value,omitempty"`
}

// Validate validates this api HTTP integration header
func (m *APIHTTPIntegrationHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api HTTP integration header based on context it is used
func (m *APIHTTPIntegrationHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIHTTPIntegrationHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIHTTPIntegrationHeader) UnmarshalBinary(b []byte) error {
	var res APIHTTPIntegrationHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
