// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// APIUrDeleteAllDeviceResponse api ur delete all device response
//
// swagger:model apiUrDeleteAllDeviceResponse
type APIUrDeleteAllDeviceResponse interface{}
