// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIEnqueueMulticastQueueItemRequest api enqueue multicast queue item request
//
// swagger:model apiEnqueueMulticastQueueItemRequest
type APIEnqueueMulticastQueueItemRequest struct {

	// Multicast queue-item object to enqueue.
	MulticastQueueItem *APIMulticastQueueItem `json:"multicastQueueItem,omitempty"`
}

// Validate validates this api enqueue multicast queue item request
func (m *APIEnqueueMulticastQueueItemRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMulticastQueueItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIEnqueueMulticastQueueItemRequest) validateMulticastQueueItem(formats strfmt.Registry) error {
	if swag.IsZero(m.MulticastQueueItem) { // not required
		return nil
	}

	if m.MulticastQueueItem != nil {
		if err := m.MulticastQueueItem.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("multicastQueueItem")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("multicastQueueItem")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this api enqueue multicast queue item request based on the context it is used
func (m *APIEnqueueMulticastQueueItemRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMulticastQueueItem(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIEnqueueMulticastQueueItemRequest) contextValidateMulticastQueueItem(ctx context.Context, formats strfmt.Registry) error {

	if m.MulticastQueueItem != nil {

		if swag.IsZero(m.MulticastQueueItem) { // not required
			return nil
		}

		if err := m.MulticastQueueItem.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("multicastQueueItem")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("multicastQueueItem")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIEnqueueMulticastQueueItemRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIEnqueueMulticastQueueItemRequest) UnmarshalBinary(b []byte) error {
	var res APIEnqueueMulticastQueueItemRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
