// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUrExportBulkDeviceResponse api ur export bulk device response
//
// swagger:model apiUrExportBulkDeviceResponse
type APIUrExportBulkDeviceResponse struct {

	// 经过base64编码的csv文件内容
	Csv string `json:"csv,omitempty"`

	// 文件名
	Filename string `json:"filename,omitempty"`
}

// Validate validates this api ur export bulk device response
func (m *APIUrExportBulkDeviceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api ur export bulk device response based on context it is used
func (m *APIUrExportBulkDeviceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUrExportBulkDeviceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUrExportBulkDeviceResponse) UnmarshalBinary(b []byte) error {
	var res APIUrExportBulkDeviceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
