// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIGetOfficialFirmwareModelsResponse api get official firmware models response
//
// swagger:model apiGetOfficialFirmwareModelsResponse
type APIGetOfficialFirmwareModelsResponse struct {

	// models
	Models []string `json:"models"`
}

// Validate validates this api get official firmware models response
func (m *APIGetOfficialFirmwareModelsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api get official firmware models response based on context it is used
func (m *APIGetOfficialFirmwareModelsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIGetOfficialFirmwareModelsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIGetOfficialFirmwareModelsResponse) UnmarshalBinary(b []byte) error {
	var res APIGetOfficialFirmwareModelsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
