// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIAddDevicePCOsResponse 添加设备 PCOs 的响应消息
//
// swagger:model apiAddDevicePCOsResponse
type APIAddDevicePCOsResponse struct {

	// 响应码 (通常 0 表示成功)
	Code int64 `json:"code,omitempty"`

	// 错误信息 (如果失败)
	Error string `json:"error,omitempty"`
}

// Validate validates this api add device p c os response
func (m *APIAddDevicePCOsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api add device p c os response based on context it is used
func (m *APIAddDevicePCOsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAddDevicePCOsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAddDevicePCOsResponse) UnmarshalBinary(b []byte) error {
	var res APIAddDevicePCOsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
