// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// APIInfluxDBPrecision api influx d b precision
//
// swagger:model apiInfluxDBPrecision
type APIInfluxDBPrecision string

func NewAPIInfluxDBPrecision(value APIInfluxDBPrecision) *APIInfluxDBPrecision {
	return &value
}

// Pointer returns a pointer to a freshly-allocated APIInfluxDBPrecision.
func (m APIInfluxDBPrecision) Pointer() *APIInfluxDBPrecision {
	return &m
}

const (

	// APIInfluxDBPrecisionNS captures enum value "NS"
	APIInfluxDBPrecisionNS APIInfluxDBPrecision = "NS"

	// APIInfluxDBPrecisionU captures enum value "U"
	APIInfluxDBPrecisionU APIInfluxDBPrecision = "U"

	// APIInfluxDBPrecisionMS captures enum value "MS"
	APIInfluxDBPrecisionMS APIInfluxDBPrecision = "MS"

	// APIInfluxDBPrecisionS captures enum value "S"
	APIInfluxDBPrecisionS APIInfluxDBPrecision = "S"

	// APIInfluxDBPrecisionM captures enum value "M"
	APIInfluxDBPrecisionM APIInfluxDBPrecision = "M"

	// APIInfluxDBPrecisionH captures enum value "H"
	APIInfluxDBPrecisionH APIInfluxDBPrecision = "H"
)

// for schema
var apiInfluxDBPrecisionEnum []interface{}

func init() {
	var res []APIInfluxDBPrecision
	if err := json.Unmarshal([]byte(`["NS","U","MS","S","M","H"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiInfluxDBPrecisionEnum = append(apiInfluxDBPrecisionEnum, v)
	}
}

func (m APIInfluxDBPrecision) validateAPIInfluxDBPrecisionEnum(path, location string, value APIInfluxDBPrecision) error {
	if err := validate.EnumCase(path, location, value, apiInfluxDBPrecisionEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this api influx d b precision
func (m APIInfluxDBPrecision) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPIInfluxDBPrecisionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this api influx d b precision based on context it is used
func (m APIInfluxDBPrecision) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
