// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUpdateGatewayRequest api update gateway request
//
// swagger:model apiUpdateGatewayRequest
type APIUpdateGatewayRequest struct {

	// Altitude of the gateway in meters
	Altitude float64 `json:"altitude,omitempty"`

	// A description for the gateway
	Description string `json:"description,omitempty"`

	// ID of the gateway-profile (optional).
	GatewayProfileID string `json:"gatewayProfileID,omitempty"`

	// Latitude of the gateway -90.0 to 90.0
	Latitude float64 `json:"latitude,omitempty"`

	// Longitude of the gateway -180.0 to 180.0
	Longitude float64 `json:"longitude,omitempty"`

	// Hex encoded mac address.
	Mac string `json:"mac,omitempty"`

	// A name for the gateway
	Name string `json:"name,omitempty"`

	// ID of the organization to which this gateway belongs.
	OrganizationID string `json:"organizationID,omitempty"`

	// Gateway sends out a periodic ping.
	Ping bool `json:"ping,omitempty"`
}

// Validate validates this api update gateway request
func (m *APIUpdateGatewayRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api update gateway request based on context it is used
func (m *APIUpdateGatewayRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUpdateGatewayRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUpdateGatewayRequest) UnmarshalBinary(b []byte) error {
	var res APIUpdateGatewayRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
