// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIObject api object
//
// swagger:model apiObject
type APIObject struct {

	// data type
	DataType string `json:"data_type,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// lora name
	LoraName string `json:"lora_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// payload codec object id
	PayloadCodecObjectID int32 `json:"payload_codec_object_id,omitempty"`

	// reference
	Reference []string `json:"reference"`

	// register addr
	RegisterAddr int32 `json:"register_addr,omitempty"`

	// register num
	RegisterNum int32 `json:"register_num,omitempty"`

	// register type
	RegisterType string `json:"register_type,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`

	// update time
	UpdateTime string `json:"update_time,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this api object
func (m *APIObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api object based on context it is used
func (m *APIObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIObject) UnmarshalBinary(b []byte) error {
	var res APIObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
