// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APICreateDeviceRequest api create device request
//
// swagger:model apiCreateDeviceRequest
type APICreateDeviceRequest struct {

	// ID of the application to which the device must be added.
	ApplicationID string `json:"applicationID,omitempty"`

	// Description of the device.
	Description string `json:"description,omitempty"`

	// Hex encoded DevEUI.
	DevEUI string `json:"devEUI,omitempty"`

	// DeviceProfileID attached to the device.
	DeviceProfileID string `json:"deviceProfileID,omitempty"`

	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `json:"name,omitempty"`

	// Skip frame-counter checks (this is insecure, but could be helpful for debugging).
	SkipFCntCheck bool `json:"skipFCntCheck,omitempty"`
}

// Validate validates this api create device request
func (m *APICreateDeviceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api create device request based on context it is used
func (m *APICreateDeviceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APICreateDeviceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APICreateDeviceRequest) UnmarshalBinary(b []byte) error {
	var res APICreateDeviceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
