// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUpdateGatewayProfileRequest api update gateway profile request
//
// swagger:model apiUpdateGatewayProfileRequest
type APIUpdateGatewayProfileRequest struct {

	// gateway profile
	GatewayProfile *APIGatewayProfile `json:"gatewayProfile,omitempty"`

	// Name of the gateway-profile.
	Name string `json:"name,omitempty"`
}

// Validate validates this api update gateway profile request
func (m *APIUpdateGatewayProfileRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGatewayProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUpdateGatewayProfileRequest) validateGatewayProfile(formats strfmt.Registry) error {
	if swag.IsZero(m.GatewayProfile) { // not required
		return nil
	}

	if m.GatewayProfile != nil {
		if err := m.GatewayProfile.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gatewayProfile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gatewayProfile")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this api update gateway profile request based on the context it is used
func (m *APIUpdateGatewayProfileRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGatewayProfile(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUpdateGatewayProfileRequest) contextValidateGatewayProfile(ctx context.Context, formats strfmt.Registry) error {

	if m.GatewayProfile != nil {

		if swag.IsZero(m.GatewayProfile) { // not required
			return nil
		}

		if err := m.GatewayProfile.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gatewayProfile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gatewayProfile")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIUpdateGatewayProfileRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUpdateGatewayProfileRequest) UnmarshalBinary(b []byte) error {
	var res APIUpdateGatewayProfileRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
