// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIUrCreateDeviceRequest api ur create device request
//
// swagger:model apiUrCreateDeviceRequest
type APIUrCreateDeviceRequest struct {

	// HEX encoded application key.
	AppKey string `json:"appKey,omitempty"`

	// Hex encoded AppSKey.
	AppSKey string `json:"appSKey,omitempty"`

	// ID of the application to which the device must be added.
	ApplicationID string `json:"applicationID,omitempty"`

	// Description of the device.
	Description string `json:"description,omitempty"`

	// Hex encoded DevAddr.
	DevAddr string `json:"devAddr,omitempty"`

	// Hex encoded DevEUI.
	DevEUI string `json:"devEUI,omitempty"`

	// Downlink frame-counter.
	FCntDown int64 `json:"fCntDown,omitempty"`

	// Uplink frame-counter.
	FCntUp int64 `json:"fCntUp,omitempty"`

	// f port
	FPort int64 `json:"fPort,omitempty"`

	// is default app key
	IsDefaultAppKey bool `json:"isDefaultAppKey,omitempty"`

	// mb frame port
	MbFramePort string `json:"mbFramePort,omitempty"`

	// mb mode
	MbMode string `json:"mbMode,omitempty"`

	// mb Tcp port
	MbTCPPort string `json:"mbTcpPort,omitempty"`

	// Name of the device (if left blank, it will be set to the DevEUI).
	Name string `json:"name,omitempty"`

	// Hex encoded NwkSKey.
	NwkSKey string `json:"nwkSKey,omitempty"`

	// payload codec ID
	PayloadCodecID string `json:"payloadCodecID,omitempty"`

	// ProfileID attached to the device.
	ProfileID string `json:"profileID,omitempty"`

	// Skip frame-counter checks (this is insecure, but could be helpful for debugging).
	SkipFCntCheck bool `json:"skipFCntCheck,omitempty"`

	// timeout
	Timeout int64 `json:"timeout,omitempty"`
}

// Validate validates this api ur create device request
func (m *APIUrCreateDeviceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api ur create device request based on context it is used
func (m *APIUrCreateDeviceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIUrCreateDeviceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUrCreateDeviceRequest) UnmarshalBinary(b []byte) error {
	var res APIUrCreateDeviceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
