// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIMAInfoResponse api m a info response
//
// swagger:model apiMAInfoResponse
type APIMAInfoResponse struct {

	// ics token exists
	IcsTokenExists bool `json:"ics_token_exists,omitempty"`

	// public key
	PublicKey string `json:"public_key,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this api m a info response
func (m *APIMAInfoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api m a info response based on context it is used
func (m *APIMAInfoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMAInfoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMAInfoResponse) UnmarshalBinary(b []byte) error {
	var res APIMAInfoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
