// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIStreamDeviceEventLogsResponse api stream device event logs response
//
// swagger:model apiStreamDeviceEventLogsResponse
type APIStreamDeviceEventLogsResponse struct {

	// The event payload in JSON encoding.
	PayloadJSON string `json:"payloadJSON,omitempty"`

	// The event type.
	Type string `json:"type,omitempty"`
}

// Validate validates this api stream device event logs response
func (m *APIStreamDeviceEventLogsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api stream device event logs response based on context it is used
func (m *APIStreamDeviceEventLogsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIStreamDeviceEventLogsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIStreamDeviceEventLogsResponse) UnmarshalBinary(b []byte) error {
	var res APIStreamDeviceEventLogsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
