// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APINOC NOC (Notification Class Object) 信息
//
// swagger:model apiNOC
type APINOC struct {

	// 是否需要确认
	AckRequired int32 `json:"ackRequired,omitempty"`

	// 描述
	Description string `json:"description,omitempty"`

	// NOC ID
	ID string `json:"id,omitempty"`

	// 实例 ID
	InstanceID int32 `json:"instanceId,omitempty"`

	// 对象名称
	ObjectName string `json:"objectName,omitempty"`

	// 接收者列表
	RecipientList []*APIRecipient `json:"recipientList"`

	// 变为故障状态的优先级
	ToFaultPriority int32 `json:"toFaultPriority,omitempty"`

	// 恢复正常状态的优先级
	ToNormalPriority int32 `json:"toNormalPriority,omitempty"`

	// 变为非正常状态的优先级
	ToOffnormalPriority int32 `json:"toOffnormalPriority,omitempty"`

	// 对象类型 ("notification-class-object")
	Type string `json:"type,omitempty"`
}

// Validate validates this api n o c
func (m *APINOC) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecipientList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APINOC) validateRecipientList(formats strfmt.Registry) error {
	if swag.IsZero(m.RecipientList) { // not required
		return nil
	}

	for i := 0; i < len(m.RecipientList); i++ {
		if swag.IsZero(m.RecipientList[i]) { // not required
			continue
		}

		if m.RecipientList[i] != nil {
			if err := m.RecipientList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recipientList" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recipientList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this api n o c based on the context it is used
func (m *APINOC) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRecipientList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APINOC) contextValidateRecipientList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RecipientList); i++ {

		if m.RecipientList[i] != nil {

			if swag.IsZero(m.RecipientList[i]) { // not required
				return nil
			}

			if err := m.RecipientList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recipientList" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recipientList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APINOC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APINOC) UnmarshalBinary(b []byte) error {
	var res APINOC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
