// Code generated by go-swagger; DO NOT EDIT.

package ursalink_bridge_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new ursalink bridge service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new ursalink bridge service API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new ursalink bridge service API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for ursalink bridge service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPIUrbridge(params *DeleteAPIUrbridgeParams, opts ...ClientOption) (*DeleteAPIUrbridgeOK, error)

	GetAPIUrbridge(params *GetAPIUrbridgeParams, opts ...ClientOption) (*GetAPIUrbridgeOK, error)

	PostAPIUrbridge(params *PostAPIUrbridgeParams, opts ...ClientOption) (*PostAPIUrbridgeOK, error)

	PutAPIUrbridge(params *PutAPIUrbridgeParams, opts ...ClientOption) (*PutAPIUrbridgeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPIUrbridge deletes deletes the bridge matching the given id
*/
func (a *Client) DeleteAPIUrbridge(params *DeleteAPIUrbridgeParams, opts ...ClientOption) (*DeleteAPIUrbridgeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAPIUrbridgeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "delete_api_urbridge",
		Method:             "DELETE",
		PathPattern:        "/api/urbridge",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteAPIUrbridgeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteAPIUrbridgeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete_api_urbridge: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIUrbridge lists lists the available profiles
*/
func (a *Client) GetAPIUrbridge(params *GetAPIUrbridgeParams, opts ...ClientOption) (*GetAPIUrbridgeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIUrbridgeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "get_api_urbridge",
		Method:             "GET",
		PathPattern:        "/api/urbridge",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAPIUrbridgeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAPIUrbridgeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_api_urbridge: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIUrbridge creates creates the given bridge
*/
func (a *Client) PostAPIUrbridge(params *PostAPIUrbridgeParams, opts ...ClientOption) (*PostAPIUrbridgeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAPIUrbridgeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "post_api_urbridge",
		Method:             "POST",
		PathPattern:        "/api/urbridge",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostAPIUrbridgeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAPIUrbridgeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post_api_urbridge: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIUrbridge updates updates the given bridge
*/
func (a *Client) PutAPIUrbridge(params *PutAPIUrbridgeParams, opts ...ClientOption) (*PutAPIUrbridgeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutAPIUrbridgeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "put_api_urbridge",
		Method:             "PUT",
		PathPattern:        "/api/urbridge",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PutAPIUrbridgeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutAPIUrbridgeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for put_api_urbridge: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
