// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetLastPingReader is a Reader for the GetLastPing structure.
type GetLastPingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLastPingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLastPingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/gateways/{mac}/pings/last] GetLastPing", response, response.Code())
	}
}

// NewGetLastPingOK creates a GetLastPingOK with default headers values
func NewGetLastPingOK() *GetLastPingOK {
	return &GetLastPingOK{}
}

/*
GetLastPingOK describes a response with status code 200, with default header values.

GetLastPingOK get last ping o k
*/
type GetLastPingOK struct {
	Payload *models.APIGetLastPingResponse
}

// IsSuccess returns true when this get last ping o k response has a 2xx status code
func (o *GetLastPingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get last ping o k response has a 3xx status code
func (o *GetLastPingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get last ping o k response has a 4xx status code
func (o *GetLastPingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get last ping o k response has a 5xx status code
func (o *GetLastPingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get last ping o k response a status code equal to that given
func (o *GetLastPingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get last ping o k response
func (o *GetLastPingOK) Code() int {
	return 200
}

func (o *GetLastPingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/gateways/{mac}/pings/last][%d] getLastPingOK %s", 200, payload)
}

func (o *GetLastPingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/gateways/{mac}/pings/last][%d] getLastPingOK %s", 200, payload)
}

func (o *GetLastPingOK) GetPayload() *models.APIGetLastPingResponse {
	return o.Payload
}

func (o *GetLastPingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetLastPingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
