// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PutAPIGatewaysByMacReader is a Reader for the PutAPIGatewaysByMac structure.
type PutAPIGatewaysByMacReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIGatewaysByMacReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIGatewaysByMacOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/gateways/{mac}] put_api_gateways_by_mac", response, response.Code())
	}
}

// NewPutAPIGatewaysByMacOK creates a PutAPIGatewaysByMacOK with default headers values
func NewPutAPIGatewaysByMacOK() *PutAPIGatewaysByMacOK {
	return &PutAPIGatewaysByMacOK{}
}

/*
PutAPIGatewaysByMacOK describes a response with status code 200, with default header values.

(empty)
*/
type PutAPIGatewaysByMacOK struct {
	Payload models.APIUpdateGatewayResponse
}

// IsSuccess returns true when this put Api gateways by mac o k response has a 2xx status code
func (o *PutAPIGatewaysByMacOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api gateways by mac o k response has a 3xx status code
func (o *PutAPIGatewaysByMacOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api gateways by mac o k response has a 4xx status code
func (o *PutAPIGatewaysByMacOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api gateways by mac o k response has a 5xx status code
func (o *PutAPIGatewaysByMacOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api gateways by mac o k response a status code equal to that given
func (o *PutAPIGatewaysByMacOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api gateways by mac o k response
func (o *PutAPIGatewaysByMacOK) Code() int {
	return 200
}

func (o *PutAPIGatewaysByMacOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/gateways/{mac}][%d] putApiGatewaysByMacOK %s", 200, payload)
}

func (o *PutAPIGatewaysByMacOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/gateways/{mac}][%d] putApiGatewaysByMacOK %s", 200, payload)
}

func (o *PutAPIGatewaysByMacOK) GetPayload() models.APIUpdateGatewayResponse {
	return o.Payload
}

func (o *PutAPIGatewaysByMacOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
