// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// UpdatePasswordReader is a Reader for the UpdatePassword structure.
type UpdatePasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdatePasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /api/users/{username}/password] UpdatePassword", response, response.Code())
	}
}

// NewUpdatePasswordOK creates a UpdatePasswordOK with default headers values
func NewUpdatePasswordOK() *UpdatePasswordOK {
	return &UpdatePasswordOK{}
}

/*
UpdatePasswordOK describes a response with status code 200, with default header values.

UpdatePasswordOK update password o k
*/
type UpdatePasswordOK struct {
	Payload models.APIUserEmptyResponse
}

// IsSuccess returns true when this update password o k response has a 2xx status code
func (o *UpdatePasswordOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update password o k response has a 3xx status code
func (o *UpdatePasswordOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update password o k response has a 4xx status code
func (o *UpdatePasswordOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update password o k response has a 5xx status code
func (o *UpdatePasswordOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update password o k response a status code equal to that given
func (o *UpdatePasswordOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update password o k response
func (o *UpdatePasswordOK) Code() int {
	return 200
}

func (o *UpdatePasswordOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/users/{username}/password][%d] updatePasswordOK %s", 200, payload)
}

func (o *UpdatePasswordOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/users/{username}/password][%d] updatePasswordOK %s", 200, payload)
}

func (o *UpdatePasswordOK) GetPayload() models.APIUserEmptyResponse {
	return o.Payload
}

func (o *UpdatePasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
