// Code generated by go-swagger; DO NOT EDIT.

package payload_codec

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIPayloadcodecsImportReader is a Reader for the GetAPIPayloadcodecsImport structure.
type GetAPIPayloadcodecsImportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPayloadcodecsImportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIPayloadcodecsImportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/payloadcodecs-import] get_api_payloadcodecs-import", response, response.Code())
	}
}

// NewGetAPIPayloadcodecsImportOK creates a GetAPIPayloadcodecsImportOK with default headers values
func NewGetAPIPayloadcodecsImportOK() *GetAPIPayloadcodecsImportOK {
	return &GetAPIPayloadcodecsImportOK{}
}

/*
GetAPIPayloadcodecsImportOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIPayloadcodecsImportOK struct {
	Payload *models.APIImportPayloadCodecResponse
}

// IsSuccess returns true when this get Api payloadcodecs import o k response has a 2xx status code
func (o *GetAPIPayloadcodecsImportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api payloadcodecs import o k response has a 3xx status code
func (o *GetAPIPayloadcodecsImportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api payloadcodecs import o k response has a 4xx status code
func (o *GetAPIPayloadcodecsImportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api payloadcodecs import o k response has a 5xx status code
func (o *GetAPIPayloadcodecsImportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api payloadcodecs import o k response a status code equal to that given
func (o *GetAPIPayloadcodecsImportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api payloadcodecs import o k response
func (o *GetAPIPayloadcodecsImportOK) Code() int {
	return 200
}

func (o *GetAPIPayloadcodecsImportOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/payloadcodecs-import][%d] getApiPayloadcodecsImportOK %s", 200, payload)
}

func (o *GetAPIPayloadcodecsImportOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/payloadcodecs-import][%d] getApiPayloadcodecsImportOK %s", 200, payload)
}

func (o *GetAPIPayloadcodecsImportOK) GetPayload() *models.APIImportPayloadCodecResponse {
	return o.Payload
}

func (o *GetAPIPayloadcodecsImportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIImportPayloadCodecResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
