// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// CreateHTTPIntegrationReader is a Reader for the CreateHTTPIntegration structure.
type CreateHTTPIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateHTTPIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateHTTPIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/applications/{id}/integrations/http] CreateHTTPIntegration", response, response.Code())
	}
}

// NewCreateHTTPIntegrationOK creates a CreateHTTPIntegrationOK with default headers values
func NewCreateHTTPIntegrationOK() *CreateHTTPIntegrationOK {
	return &CreateHTTPIntegrationOK{}
}

/*
CreateHTTPIntegrationOK describes a response with status code 200, with default header values.

CreateHTTPIntegrationOK create Http integration o k
*/
type CreateHTTPIntegrationOK struct {
	Payload models.APIEmptyResponse
}

// IsSuccess returns true when this create Http integration o k response has a 2xx status code
func (o *CreateHTTPIntegrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create Http integration o k response has a 3xx status code
func (o *CreateHTTPIntegrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create Http integration o k response has a 4xx status code
func (o *CreateHTTPIntegrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create Http integration o k response has a 5xx status code
func (o *CreateHTTPIntegrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create Http integration o k response a status code equal to that given
func (o *CreateHTTPIntegrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create Http integration o k response
func (o *CreateHTTPIntegrationOK) Code() int {
	return 200
}

func (o *CreateHTTPIntegrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/applications/{id}/integrations/http][%d] createHttpIntegrationOK %s", 200, payload)
}

func (o *CreateHTTPIntegrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/applications/{id}/integrations/http][%d] createHttpIntegrationOK %s", 200, payload)
}

func (o *CreateHTTPIntegrationOK) GetPayload() models.APIEmptyResponse {
	return o.Payload
}

func (o *CreateHTTPIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
