// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// DeleteHTTPIntegrationReader is a Reader for the DeleteHTTPIntegration structure.
type DeleteHTTPIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHTTPIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteHTTPIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/applications/{id}/integrations/http] DeleteHTTPIntegration", response, response.Code())
	}
}

// NewDeleteHTTPIntegrationOK creates a DeleteHTTPIntegrationOK with default headers values
func NewDeleteHTTPIntegrationOK() *DeleteHTTPIntegrationOK {
	return &DeleteHTTPIntegrationOK{}
}

/*
DeleteHTTPIntegrationOK describes a response with status code 200, with default header values.

DeleteHTTPIntegrationOK delete Http integration o k
*/
type DeleteHTTPIntegrationOK struct {
	Payload models.APIEmptyResponse
}

// IsSuccess returns true when this delete Http integration o k response has a 2xx status code
func (o *DeleteHTTPIntegrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Http integration o k response has a 3xx status code
func (o *DeleteHTTPIntegrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Http integration o k response has a 4xx status code
func (o *DeleteHTTPIntegrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Http integration o k response has a 5xx status code
func (o *DeleteHTTPIntegrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Http integration o k response a status code equal to that given
func (o *DeleteHTTPIntegrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Http integration o k response
func (o *DeleteHTTPIntegrationOK) Code() int {
	return 200
}

func (o *DeleteHTTPIntegrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/applications/{id}/integrations/http][%d] deleteHttpIntegrationOK %s", 200, payload)
}

func (o *DeleteHTTPIntegrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/applications/{id}/integrations/http][%d] deleteHttpIntegrationOK %s", 200, payload)
}

func (o *DeleteHTTPIntegrationOK) GetPayload() models.APIEmptyResponse {
	return o.Payload
}

func (o *DeleteHTTPIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
