// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIApplicationsIntegrationsHTTPByIDParams creates a new DeleteAPIApplicationsIntegrationsHTTPByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIApplicationsIntegrationsHTTPByIDParams() *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	return &DeleteAPIApplicationsIntegrationsHTTPByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithTimeout creates a new DeleteAPIApplicationsIntegrationsHTTPByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithTimeout(timeout time.Duration) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	return &DeleteAPIApplicationsIntegrationsHTTPByIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithContext creates a new DeleteAPIApplicationsIntegrationsHTTPByIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithContext(ctx context.Context) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	return &DeleteAPIApplicationsIntegrationsHTTPByIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithHTTPClient creates a new DeleteAPIApplicationsIntegrationsHTTPByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIApplicationsIntegrationsHTTPByIDParamsWithHTTPClient(client *http.Client) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	return &DeleteAPIApplicationsIntegrationsHTTPByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIApplicationsIntegrationsHTTPByIDParams contains all the parameters to send to the API endpoint

	for the delete api applications integrations http by id operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIApplicationsIntegrationsHTTPByIDParams struct {

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete api applications integrations http by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WithDefaults() *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete api applications integrations http by id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WithTimeout(timeout time.Duration) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WithContext(ctx context.Context) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WithHTTPClient(client *http.Client) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WithID(id string) *DeleteAPIApplicationsIntegrationsHTTPByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete api applications integrations http by id params
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIApplicationsIntegrationsHTTPByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
