// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetInfluxDBIntegrationReader is a Reader for the GetInfluxDBIntegration structure.
type GetInfluxDBIntegrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInfluxDBIntegrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInfluxDBIntegrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/applications/{application_id}/integrations/influxdb] GetInfluxDBIntegration", response, response.Code())
	}
}

// NewGetInfluxDBIntegrationOK creates a GetInfluxDBIntegrationOK with default headers values
func NewGetInfluxDBIntegrationOK() *GetInfluxDBIntegrationOK {
	return &GetInfluxDBIntegrationOK{}
}

/*
GetInfluxDBIntegrationOK describes a response with status code 200, with default header values.

GetInfluxDBIntegrationOK get influx d b integration o k
*/
type GetInfluxDBIntegrationOK struct {
	Payload *models.APIGetInfluxDBIntegrationResponse
}

// IsSuccess returns true when this get influx d b integration o k response has a 2xx status code
func (o *GetInfluxDBIntegrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get influx d b integration o k response has a 3xx status code
func (o *GetInfluxDBIntegrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get influx d b integration o k response has a 4xx status code
func (o *GetInfluxDBIntegrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get influx d b integration o k response has a 5xx status code
func (o *GetInfluxDBIntegrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get influx d b integration o k response a status code equal to that given
func (o *GetInfluxDBIntegrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get influx d b integration o k response
func (o *GetInfluxDBIntegrationOK) Code() int {
	return 200
}

func (o *GetInfluxDBIntegrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{application_id}/integrations/influxdb][%d] getInfluxDBIntegrationOK %s", 200, payload)
}

func (o *GetInfluxDBIntegrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{application_id}/integrations/influxdb][%d] getInfluxDBIntegrationOK %s", 200, payload)
}

func (o *GetInfluxDBIntegrationOK) GetPayload() *models.APIGetInfluxDBIntegrationResponse {
	return o.Payload
}

func (o *GetInfluxDBIntegrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetInfluxDBIntegrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
