// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIApplicationsIntegrationsInfluxdbByApplicationIDReader is a Reader for the GetAPIApplicationsIntegrationsInfluxdbByApplicationID structure.
type GetAPIApplicationsIntegrationsInfluxdbByApplicationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/applications/{application_id}/integrations/influxdb] get_api_applications_integrations_influxdb_by_application_id", response, response.Code())
	}
}

// NewGetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK creates a GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK with default headers values
func NewGetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK() *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK {
	return &GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK{}
}

/*
GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK struct {
	Payload *models.APIGetInfluxDBIntegrationResponse
}

// IsSuccess returns true when this get Api applications integrations influxdb by application Id o k response has a 2xx status code
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api applications integrations influxdb by application Id o k response has a 3xx status code
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api applications integrations influxdb by application Id o k response has a 4xx status code
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api applications integrations influxdb by application Id o k response has a 5xx status code
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api applications integrations influxdb by application Id o k response a status code equal to that given
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api applications integrations influxdb by application Id o k response
func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) Code() int {
	return 200
}

func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{application_id}/integrations/influxdb][%d] getApiApplicationsIntegrationsInfluxdbByApplicationIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{application_id}/integrations/influxdb][%d] getApiApplicationsIntegrationsInfluxdbByApplicationIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) GetPayload() *models.APIGetInfluxDBIntegrationResponse {
	return o.Payload
}

func (o *GetAPIApplicationsIntegrationsInfluxdbByApplicationIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetInfluxDBIntegrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
