// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHTTPIntegrationParams creates a new GetHTTPIntegrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHTTPIntegrationParams() *GetHTTPIntegrationParams {
	return &GetHTTPIntegrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHTTPIntegrationParamsWithTimeout creates a new GetHTTPIntegrationParams object
// with the ability to set a timeout on a request.
func NewGetHTTPIntegrationParamsWithTimeout(timeout time.Duration) *GetHTTPIntegrationParams {
	return &GetHTTPIntegrationParams{
		timeout: timeout,
	}
}

// NewGetHTTPIntegrationParamsWithContext creates a new GetHTTPIntegrationParams object
// with the ability to set a context for a request.
func NewGetHTTPIntegrationParamsWithContext(ctx context.Context) *GetHTTPIntegrationParams {
	return &GetHTTPIntegrationParams{
		Context: ctx,
	}
}

// NewGetHTTPIntegrationParamsWithHTTPClient creates a new GetHTTPIntegrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHTTPIntegrationParamsWithHTTPClient(client *http.Client) *GetHTTPIntegrationParams {
	return &GetHTTPIntegrationParams{
		HTTPClient: client,
	}
}

/*
GetHTTPIntegrationParams contains all the parameters to send to the API endpoint

	for the get HTTP integration operation.

	Typically these are written to a http.Request.
*/
type GetHTTPIntegrationParams struct {

	/* ID.

	   The id of the application.

	   Format: int64
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get HTTP integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPIntegrationParams) WithDefaults() *GetHTTPIntegrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get HTTP integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHTTPIntegrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get HTTP integration params
func (o *GetHTTPIntegrationParams) WithTimeout(timeout time.Duration) *GetHTTPIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get HTTP integration params
func (o *GetHTTPIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get HTTP integration params
func (o *GetHTTPIntegrationParams) WithContext(ctx context.Context) *GetHTTPIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get HTTP integration params
func (o *GetHTTPIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get HTTP integration params
func (o *GetHTTPIntegrationParams) WithHTTPClient(client *http.Client) *GetHTTPIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get HTTP integration params
func (o *GetHTTPIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get HTTP integration params
func (o *GetHTTPIntegrationParams) WithID(id string) *GetHTTPIntegrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get HTTP integration params
func (o *GetHTTPIntegrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetHTTPIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
