// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIApplicationsParams creates a new GetAPIApplicationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIApplicationsParams() *GetAPIApplicationsParams {
	return &GetAPIApplicationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIApplicationsParamsWithTimeout creates a new GetAPIApplicationsParams object
// with the ability to set a timeout on a request.
func NewGetAPIApplicationsParamsWithTimeout(timeout time.Duration) *GetAPIApplicationsParams {
	return &GetAPIApplicationsParams{
		timeout: timeout,
	}
}

// NewGetAPIApplicationsParamsWithContext creates a new GetAPIApplicationsParams object
// with the ability to set a context for a request.
func NewGetAPIApplicationsParamsWithContext(ctx context.Context) *GetAPIApplicationsParams {
	return &GetAPIApplicationsParams{
		Context: ctx,
	}
}

// NewGetAPIApplicationsParamsWithHTTPClient creates a new GetAPIApplicationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIApplicationsParamsWithHTTPClient(client *http.Client) *GetAPIApplicationsParams {
	return &GetAPIApplicationsParams{
		HTTPClient: client,
	}
}

/*
GetAPIApplicationsParams contains all the parameters to send to the API endpoint

	for the get api applications operation.

	Typically these are written to a http.Request.
*/
type GetAPIApplicationsParams struct {

	/* Limit.

	   Max number of applications to return in the result-test.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset in the result-set (for pagination).

	   Format: int64
	*/
	Offset *string

	/* OrganizationID.

	   ID of the organization to filter on.

	   Format: int64
	*/
	OrganizationID *string

	/* Search.

	   Search on name (optional).
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get api applications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApplicationsParams) WithDefaults() *GetAPIApplicationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get api applications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIApplicationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get api applications params
func (o *GetAPIApplicationsParams) WithTimeout(timeout time.Duration) *GetAPIApplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get api applications params
func (o *GetAPIApplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get api applications params
func (o *GetAPIApplicationsParams) WithContext(ctx context.Context) *GetAPIApplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get api applications params
func (o *GetAPIApplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get api applications params
func (o *GetAPIApplicationsParams) WithHTTPClient(client *http.Client) *GetAPIApplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get api applications params
func (o *GetAPIApplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get api applications params
func (o *GetAPIApplicationsParams) WithLimit(limit *string) *GetAPIApplicationsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get api applications params
func (o *GetAPIApplicationsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the get api applications params
func (o *GetAPIApplicationsParams) WithOffset(offset *string) *GetAPIApplicationsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get api applications params
func (o *GetAPIApplicationsParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get api applications params
func (o *GetAPIApplicationsParams) WithOrganizationID(organizationID *string) *GetAPIApplicationsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get api applications params
func (o *GetAPIApplicationsParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WithSearch adds the search to the get api applications params
func (o *GetAPIApplicationsParams) WithSearch(search *string) *GetAPIApplicationsParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get api applications params
func (o *GetAPIApplicationsParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIApplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationID
		var qrOrganizationID string

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationID", qOrganizationID); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
