// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIApplicationsByIDReader is a Reader for the GetAPIApplicationsByID structure.
type GetAPIApplicationsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIApplicationsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIApplicationsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/applications/{id}] get_api_applications_by_id", response, response.Code())
	}
}

// NewGetAPIApplicationsByIDOK creates a GetAPIApplicationsByIDOK with default headers values
func NewGetAPIApplicationsByIDOK() *GetAPIApplicationsByIDOK {
	return &GetAPIApplicationsByIDOK{}
}

/*
GetAPIApplicationsByIDOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIApplicationsByIDOK struct {
	Payload *models.APIGetApplicationResponse
}

// IsSuccess returns true when this get Api applications by Id o k response has a 2xx status code
func (o *GetAPIApplicationsByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api applications by Id o k response has a 3xx status code
func (o *GetAPIApplicationsByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api applications by Id o k response has a 4xx status code
func (o *GetAPIApplicationsByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api applications by Id o k response has a 5xx status code
func (o *GetAPIApplicationsByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api applications by Id o k response a status code equal to that given
func (o *GetAPIApplicationsByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api applications by Id o k response
func (o *GetAPIApplicationsByIDOK) Code() int {
	return 200
}

func (o *GetAPIApplicationsByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{id}][%d] getApiApplicationsByIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/applications/{id}][%d] getApiApplicationsByIdOK %s", 200, payload)
}

func (o *GetAPIApplicationsByIDOK) GetPayload() *models.APIGetApplicationResponse {
	return o.Payload
}

func (o *GetAPIApplicationsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetApplicationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
