#!/bin/sh /etc/rc.common
# Copyright (C) 2018 URSALINK

USE_PROCD=1
START=99
STOP=99
PROG="/usr/bin/lora-app-server"
SERVCONFIG="/etc/lora-app-server/lora-app-server.toml"

wait_mosquitto() {
    mos=`ps | grep mosquitto | grep -v grep`
    times=1
    until [ "$mos" ] || [ $times -eq 30 ]
    do
        sleep 1
        mos=`ps | grep mosquitto | grep -v grep`
        times=$(($times+1))
    done
    [ "$mos" == "" ] && exit 1
}

wait_redis() {
    redis=`ps | grep redis-server | grep -v grep`
    times=1
    until [ "$redis" ] || [ $times -eq 30 ]
    do
        sleep 1
        redis=`ps | grep redis-server | grep -v grep`
        times=$(($times+1))
    done
    [ "$redis" == "" ] && exit 1
}

wait_postgresql() {
    sql=`ps | grep postmaster | grep -v grep`
    times=1
    until [ "$sql" ] || [ $times -eq 30 ]
    do
        sleep 1
        sql=`ps | grep postmaster | grep -v grep`
        times=$(($times+1))
    done
    [ "$sql" == "" ] && exit 1
}

wait_configfile() {
    if  [ ! -e $SERVCONFIG ]; then
    	lora-app-server configfile > $SERVCONFIG
    fi
        filesize=`ls -l $SERVCONFIG | awk '{print $5}'`
    if [ $filesize -lt 10 ];then
        lora-app-server configfile > $SERVCONFIG
    fi
}


start_service() {
    wait_mosquitto
    wait_redis
    wait_postgresql
	wait_configfile
    procd_open_instance
    procd_set_param command "$PROG" -c $SERVCONFIG
    procd_set_param pidfile /var/run/lora-app-server.pid
    procd_set_param respawn
    procd_close_instance
}

# stop_service() {
#     service_stop $PROG
# }
