// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewCreateFuotaTaskParams creates a new CreateFuotaTaskParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateFuotaTaskParams() *CreateFuotaTaskParams {
	return &CreateFuotaTaskParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateFuotaTaskParamsWithTimeout creates a new CreateFuotaTaskParams object
// with the ability to set a timeout on a request.
func NewCreateFuotaTaskParamsWithTimeout(timeout time.Duration) *CreateFuotaTaskParams {
	return &CreateFuotaTaskParams{
		timeout: timeout,
	}
}

// NewCreateFuotaTaskParamsWithContext creates a new CreateFuotaTaskParams object
// with the ability to set a context for a request.
func NewCreateFuotaTaskParamsWithContext(ctx context.Context) *CreateFuotaTaskParams {
	return &CreateFuotaTaskParams{
		Context: ctx,
	}
}

// NewCreateFuotaTaskParamsWithHTTPClient creates a new CreateFuotaTaskParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateFuotaTaskParamsWithHTTPClient(client *http.Client) *CreateFuotaTaskParams {
	return &CreateFuotaTaskParams{
		HTTPClient: client,
	}
}

/*
CreateFuotaTaskParams contains all the parameters to send to the API endpoint

	for the create fuota task operation.

	Typically these are written to a http.Request.
*/
type CreateFuotaTaskParams struct {

	// Body.
	Body *models.APICreateFuotaTaskRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create fuota task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateFuotaTaskParams) WithDefaults() *CreateFuotaTaskParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create fuota task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateFuotaTaskParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create fuota task params
func (o *CreateFuotaTaskParams) WithTimeout(timeout time.Duration) *CreateFuotaTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create fuota task params
func (o *CreateFuotaTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create fuota task params
func (o *CreateFuotaTaskParams) WithContext(ctx context.Context) *CreateFuotaTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create fuota task params
func (o *CreateFuotaTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create fuota task params
func (o *CreateFuotaTaskParams) WithHTTPClient(client *http.Client) *CreateFuotaTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create fuota task params
func (o *CreateFuotaTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create fuota task params
func (o *CreateFuotaTaskParams) WithBody(body *models.APICreateFuotaTaskRequest) *CreateFuotaTaskParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create fuota task params
func (o *CreateFuotaTaskParams) SetBody(body *models.APICreateFuotaTaskRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateFuotaTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
