// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFuotaDevicesParams creates a new GetFuotaDevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFuotaDevicesParams() *GetFuotaDevicesParams {
	return &GetFuotaDevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFuotaDevicesParamsWithTimeout creates a new GetFuotaDevicesParams object
// with the ability to set a timeout on a request.
func NewGetFuotaDevicesParamsWithTimeout(timeout time.Duration) *GetFuotaDevicesParams {
	return &GetFuotaDevicesParams{
		timeout: timeout,
	}
}

// NewGetFuotaDevicesParamsWithContext creates a new GetFuotaDevicesParams object
// with the ability to set a context for a request.
func NewGetFuotaDevicesParamsWithContext(ctx context.Context) *GetFuotaDevicesParams {
	return &GetFuotaDevicesParams{
		Context: ctx,
	}
}

// NewGetFuotaDevicesParamsWithHTTPClient creates a new GetFuotaDevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFuotaDevicesParamsWithHTTPClient(client *http.Client) *GetFuotaDevicesParams {
	return &GetFuotaDevicesParams{
		HTTPClient: client,
	}
}

/*
GetFuotaDevicesParams contains all the parameters to send to the API endpoint

	for the get fuota devices operation.

	Typically these are written to a http.Request.
*/
type GetFuotaDevicesParams struct {

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Offset.
	//
	// Format: int32
	Offset *int32

	// Search.
	Search *string

	// TaskID.
	//
	// Format: int32
	TaskID *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fuota devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFuotaDevicesParams) WithDefaults() *GetFuotaDevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fuota devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFuotaDevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fuota devices params
func (o *GetFuotaDevicesParams) WithTimeout(timeout time.Duration) *GetFuotaDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fuota devices params
func (o *GetFuotaDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fuota devices params
func (o *GetFuotaDevicesParams) WithContext(ctx context.Context) *GetFuotaDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fuota devices params
func (o *GetFuotaDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fuota devices params
func (o *GetFuotaDevicesParams) WithHTTPClient(client *http.Client) *GetFuotaDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fuota devices params
func (o *GetFuotaDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get fuota devices params
func (o *GetFuotaDevicesParams) WithLimit(limit *int32) *GetFuotaDevicesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get fuota devices params
func (o *GetFuotaDevicesParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get fuota devices params
func (o *GetFuotaDevicesParams) WithOffset(offset *int32) *GetFuotaDevicesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get fuota devices params
func (o *GetFuotaDevicesParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithSearch adds the search to the get fuota devices params
func (o *GetFuotaDevicesParams) WithSearch(search *string) *GetFuotaDevicesParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get fuota devices params
func (o *GetFuotaDevicesParams) SetSearch(search *string) {
	o.Search = search
}

// WithTaskID adds the taskID to the get fuota devices params
func (o *GetFuotaDevicesParams) WithTaskID(taskID *int32) *GetFuotaDevicesParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get fuota devices params
func (o *GetFuotaDevicesParams) SetTaskID(taskID *int32) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFuotaDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if o.TaskID != nil {

		// query param task_id
		var qrTaskID int32

		if o.TaskID != nil {
			qrTaskID = *o.TaskID
		}
		qTaskID := swag.FormatInt32(qrTaskID)
		if qTaskID != "" {

			if err := r.SetQueryParam("task_id", qTaskID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
