// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIFuotaOfficialModelsReader is a Reader for the GetAPIFuotaOfficialModels structure.
type GetAPIFuotaOfficialModelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIFuotaOfficialModelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIFuotaOfficialModelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/fuota/official/models] get_api_fuota_official_models", response, response.Code())
	}
}

// NewGetAPIFuotaOfficialModelsOK creates a GetAPIFuotaOfficialModelsOK with default headers values
func NewGetAPIFuotaOfficialModelsOK() *GetAPIFuotaOfficialModelsOK {
	return &GetAPIFuotaOfficialModelsOK{}
}

/*
GetAPIFuotaOfficialModelsOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIFuotaOfficialModelsOK struct {
	Payload *models.APIGetOfficialFirmwareModelsResponse
}

// IsSuccess returns true when this get Api fuota official models o k response has a 2xx status code
func (o *GetAPIFuotaOfficialModelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api fuota official models o k response has a 3xx status code
func (o *GetAPIFuotaOfficialModelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api fuota official models o k response has a 4xx status code
func (o *GetAPIFuotaOfficialModelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api fuota official models o k response has a 5xx status code
func (o *GetAPIFuotaOfficialModelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api fuota official models o k response a status code equal to that given
func (o *GetAPIFuotaOfficialModelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api fuota official models o k response
func (o *GetAPIFuotaOfficialModelsOK) Code() int {
	return 200
}

func (o *GetAPIFuotaOfficialModelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/fuota/official/models][%d] getApiFuotaOfficialModelsOK %s", 200, payload)
}

func (o *GetAPIFuotaOfficialModelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/fuota/official/models][%d] getApiFuotaOfficialModelsOK %s", 200, payload)
}

func (o *GetAPIFuotaOfficialModelsOK) GetPayload() *models.APIGetOfficialFirmwareModelsResponse {
	return o.Payload
}

func (o *GetAPIFuotaOfficialModelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGetOfficialFirmwareModelsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
