// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// GetAPIFuotaTaskReader is a Reader for the GetAPIFuotaTask structure.
type GetAPIFuotaTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIFuotaTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIFuotaTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/fuota/task] get_api_fuota_task", response, response.Code())
	}
}

// NewGetAPIFuotaTaskOK creates a GetAPIFuotaTaskOK with default headers values
func NewGetAPIFuotaTaskOK() *GetAPIFuotaTaskOK {
	return &GetAPIFuotaTaskOK{}
}

/*
GetAPIFuotaTaskOK describes a response with status code 200, with default header values.

(empty)
*/
type GetAPIFuotaTaskOK struct {
	Payload *models.APIListFuotaTasksResponse
}

// IsSuccess returns true when this get Api fuota task o k response has a 2xx status code
func (o *GetAPIFuotaTaskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api fuota task o k response has a 3xx status code
func (o *GetAPIFuotaTaskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api fuota task o k response has a 4xx status code
func (o *GetAPIFuotaTaskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api fuota task o k response has a 5xx status code
func (o *GetAPIFuotaTaskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api fuota task o k response a status code equal to that given
func (o *GetAPIFuotaTaskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api fuota task o k response
func (o *GetAPIFuotaTaskOK) Code() int {
	return 200
}

func (o *GetAPIFuotaTaskOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/fuota/task][%d] getApiFuotaTaskOK %s", 200, payload)
}

func (o *GetAPIFuotaTaskOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/fuota/task][%d] getApiFuotaTaskOK %s", 200, payload)
}

func (o *GetAPIFuotaTaskOK) GetPayload() *models.APIListFuotaTasksResponse {
	return o.Payload
}

func (o *GetAPIFuotaTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIListFuotaTasksResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
