// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPostAPIFuotaDevicesFirmwareParams creates a new PostAPIFuotaDevicesFirmwareParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIFuotaDevicesFirmwareParams() *PostAPIFuotaDevicesFirmwareParams {
	return &PostAPIFuotaDevicesFirmwareParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIFuotaDevicesFirmwareParamsWithTimeout creates a new PostAPIFuotaDevicesFirmwareParams object
// with the ability to set a timeout on a request.
func NewPostAPIFuotaDevicesFirmwareParamsWithTimeout(timeout time.Duration) *PostAPIFuotaDevicesFirmwareParams {
	return &PostAPIFuotaDevicesFirmwareParams{
		timeout: timeout,
	}
}

// NewPostAPIFuotaDevicesFirmwareParamsWithContext creates a new PostAPIFuotaDevicesFirmwareParams object
// with the ability to set a context for a request.
func NewPostAPIFuotaDevicesFirmwareParamsWithContext(ctx context.Context) *PostAPIFuotaDevicesFirmwareParams {
	return &PostAPIFuotaDevicesFirmwareParams{
		Context: ctx,
	}
}

// NewPostAPIFuotaDevicesFirmwareParamsWithHTTPClient creates a new PostAPIFuotaDevicesFirmwareParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIFuotaDevicesFirmwareParamsWithHTTPClient(client *http.Client) *PostAPIFuotaDevicesFirmwareParams {
	return &PostAPIFuotaDevicesFirmwareParams{
		HTTPClient: client,
	}
}

/*
PostAPIFuotaDevicesFirmwareParams contains all the parameters to send to the API endpoint

	for the post api fuota devices firmware operation.

	Typically these are written to a http.Request.
*/
type PostAPIFuotaDevicesFirmwareParams struct {

	// Body.
	Body *models.APIGetDevicesByFirmwareInfoRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post api fuota devices firmware params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIFuotaDevicesFirmwareParams) WithDefaults() *PostAPIFuotaDevicesFirmwareParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post api fuota devices firmware params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIFuotaDevicesFirmwareParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) WithTimeout(timeout time.Duration) *PostAPIFuotaDevicesFirmwareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) WithContext(ctx context.Context) *PostAPIFuotaDevicesFirmwareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) WithHTTPClient(client *http.Client) *PostAPIFuotaDevicesFirmwareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) WithBody(body *models.APIGetDevicesByFirmwareInfoRequest) *PostAPIFuotaDevicesFirmwareParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post api fuota devices firmware params
func (o *PostAPIFuotaDevicesFirmwareParams) SetBody(body *models.APIGetDevicesByFirmwareInfoRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIFuotaDevicesFirmwareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
