// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIFuotaTaskDeleteReader is a Reader for the PostAPIFuotaTaskDelete structure.
type PostAPIFuotaTaskDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIFuotaTaskDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIFuotaTaskDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/fuota/task/delete] post_api_fuota_task_delete", response, response.Code())
	}
}

// NewPostAPIFuotaTaskDeleteOK creates a PostAPIFuotaTaskDeleteOK with default headers values
func NewPostAPIFuotaTaskDeleteOK() *PostAPIFuotaTaskDeleteOK {
	return &PostAPIFuotaTaskDeleteOK{}
}

/*
PostAPIFuotaTaskDeleteOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIFuotaTaskDeleteOK struct {
	Payload models.APIDeleteFuotaTaskResponse
}

// IsSuccess returns true when this post Api fuota task delete o k response has a 2xx status code
func (o *PostAPIFuotaTaskDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api fuota task delete o k response has a 3xx status code
func (o *PostAPIFuotaTaskDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api fuota task delete o k response has a 4xx status code
func (o *PostAPIFuotaTaskDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api fuota task delete o k response has a 5xx status code
func (o *PostAPIFuotaTaskDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api fuota task delete o k response a status code equal to that given
func (o *PostAPIFuotaTaskDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api fuota task delete o k response
func (o *PostAPIFuotaTaskDeleteOK) Code() int {
	return 200
}

func (o *PostAPIFuotaTaskDeleteOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/fuota/task/delete][%d] postApiFuotaTaskDeleteOK %s", 200, payload)
}

func (o *PostAPIFuotaTaskDeleteOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/fuota/task/delete][%d] postApiFuotaTaskDeleteOK %s", 200, payload)
}

func (o *PostAPIFuotaTaskDeleteOK) GetPayload() models.APIDeleteFuotaTaskResponse {
	return o.Payload
}

func (o *PostAPIFuotaTaskDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
