// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// PostAPIFuotaTaskRetryReader is a Reader for the PostAPIFuotaTaskRetry structure.
type PostAPIFuotaTaskRetryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIFuotaTaskRetryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIFuotaTaskRetryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/fuota/task/retry] post_api_fuota_task_retry", response, response.Code())
	}
}

// NewPostAPIFuotaTaskRetryOK creates a PostAPIFuotaTaskRetryOK with default headers values
func NewPostAPIFuotaTaskRetryOK() *PostAPIFuotaTaskRetryOK {
	return &PostAPIFuotaTaskRetryOK{}
}

/*
PostAPIFuotaTaskRetryOK describes a response with status code 200, with default header values.

(empty)
*/
type PostAPIFuotaTaskRetryOK struct {
	Payload models.APIRetryFuotaTaskResponse
}

// IsSuccess returns true when this post Api fuota task retry o k response has a 2xx status code
func (o *PostAPIFuotaTaskRetryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api fuota task retry o k response has a 3xx status code
func (o *PostAPIFuotaTaskRetryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api fuota task retry o k response has a 4xx status code
func (o *PostAPIFuotaTaskRetryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api fuota task retry o k response has a 5xx status code
func (o *PostAPIFuotaTaskRetryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api fuota task retry o k response a status code equal to that given
func (o *PostAPIFuotaTaskRetryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api fuota task retry o k response
func (o *PostAPIFuotaTaskRetryOK) Code() int {
	return 200
}

func (o *PostAPIFuotaTaskRetryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/fuota/task/retry][%d] postApiFuotaTaskRetryOK %s", 200, payload)
}

func (o *PostAPIFuotaTaskRetryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/fuota/task/retry][%d] postApiFuotaTaskRetryOK %s", 200, payload)
}

func (o *PostAPIFuotaTaskRetryOK) GetPayload() models.APIRetryFuotaTaskResponse {
	return o.Payload
}

func (o *PostAPIFuotaTaskRetryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
