// Code generated by go-swagger; DO NOT EDIT.

package fuota_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/brocaar/lora-simulator/internal/as_api/models"
)

// NewPutAPIFuotaTaskParams creates a new PutAPIFuotaTaskParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIFuotaTaskParams() *PutAPIFuotaTaskParams {
	return &PutAPIFuotaTaskParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIFuotaTaskParamsWithTimeout creates a new PutAPIFuotaTaskParams object
// with the ability to set a timeout on a request.
func NewPutAPIFuotaTaskParamsWithTimeout(timeout time.Duration) *PutAPIFuotaTaskParams {
	return &PutAPIFuotaTaskParams{
		timeout: timeout,
	}
}

// NewPutAPIFuotaTaskParamsWithContext creates a new PutAPIFuotaTaskParams object
// with the ability to set a context for a request.
func NewPutAPIFuotaTaskParamsWithContext(ctx context.Context) *PutAPIFuotaTaskParams {
	return &PutAPIFuotaTaskParams{
		Context: ctx,
	}
}

// NewPutAPIFuotaTaskParamsWithHTTPClient creates a new PutAPIFuotaTaskParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIFuotaTaskParamsWithHTTPClient(client *http.Client) *PutAPIFuotaTaskParams {
	return &PutAPIFuotaTaskParams{
		HTTPClient: client,
	}
}

/*
PutAPIFuotaTaskParams contains all the parameters to send to the API endpoint

	for the put api fuota task operation.

	Typically these are written to a http.Request.
*/
type PutAPIFuotaTaskParams struct {

	// Body.
	Body *models.APIUpdateFuotaTaskRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put api fuota task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIFuotaTaskParams) WithDefaults() *PutAPIFuotaTaskParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put api fuota task params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIFuotaTaskParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put api fuota task params
func (o *PutAPIFuotaTaskParams) WithTimeout(timeout time.Duration) *PutAPIFuotaTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put api fuota task params
func (o *PutAPIFuotaTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put api fuota task params
func (o *PutAPIFuotaTaskParams) WithContext(ctx context.Context) *PutAPIFuotaTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put api fuota task params
func (o *PutAPIFuotaTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put api fuota task params
func (o *PutAPIFuotaTaskParams) WithHTTPClient(client *http.Client) *PutAPIFuotaTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put api fuota task params
func (o *PutAPIFuotaTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put api fuota task params
func (o *PutAPIFuotaTaskParams) WithBody(body *models.APIUpdateFuotaTaskRequest) *PutAPIFuotaTaskParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put api fuota task params
func (o *PutAPIFuotaTaskParams) SetBody(body *models.APIUpdateFuotaTaskRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIFuotaTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
