// Code generated by go-swagger; DO NOT EDIT.

package service_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIServiceProfilesParams creates a new GetAPIServiceProfilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIServiceProfilesParams() *GetAPIServiceProfilesParams {
	return &GetAPIServiceProfilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIServiceProfilesParamsWithTimeout creates a new GetAPIServiceProfilesParams object
// with the ability to set a timeout on a request.
func NewGetAPIServiceProfilesParamsWithTimeout(timeout time.Duration) *GetAPIServiceProfilesParams {
	return &GetAPIServiceProfilesParams{
		timeout: timeout,
	}
}

// NewGetAPIServiceProfilesParamsWithContext creates a new GetAPIServiceProfilesParams object
// with the ability to set a context for a request.
func NewGetAPIServiceProfilesParamsWithContext(ctx context.Context) *GetAPIServiceProfilesParams {
	return &GetAPIServiceProfilesParams{
		Context: ctx,
	}
}

// NewGetAPIServiceProfilesParamsWithHTTPClient creates a new GetAPIServiceProfilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIServiceProfilesParamsWithHTTPClient(client *http.Client) *GetAPIServiceProfilesParams {
	return &GetAPIServiceProfilesParams{
		HTTPClient: client,
	}
}

/*
GetAPIServiceProfilesParams contains all the parameters to send to the API endpoint

	for the get api service profiles operation.

	Typically these are written to a http.Request.
*/
type GetAPIServiceProfilesParams struct {

	/* Limit.

	   Max number of items to return.

	   Format: int64
	*/
	Limit *string

	/* Offset.

	   Offset in the result-set (for pagination).

	   Format: int64
	*/
	Offset *string

	/* OrganizationID.

	   Organization id to filter on.

	   Format: int64
	*/
	OrganizationID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get api service profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIServiceProfilesParams) WithDefaults() *GetAPIServiceProfilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get api service profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIServiceProfilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithTimeout(timeout time.Duration) *GetAPIServiceProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithContext(ctx context.Context) *GetAPIServiceProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithHTTPClient(client *http.Client) *GetAPIServiceProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithLimit(limit *string) *GetAPIServiceProfilesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithOffset adds the offset to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithOffset(offset *string) *GetAPIServiceProfilesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get api service profiles params
func (o *GetAPIServiceProfilesParams) WithOrganizationID(organizationID *string) *GetAPIServiceProfilesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get api service profiles params
func (o *GetAPIServiceProfilesParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIServiceProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationID
		var qrOrganizationID string

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationID", qOrganizationID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
